### ISSUE TITLE
KeyError when deleting pending response ID in on_send_request_done

### ISSUE THREAD

**Issue by dset0x** [Azure/azure-iot-sdk-python#1001]
Hello,

# Context

- **OS and version used:** Raspbian Buster
- **Python version:** Python 3.7.3
- **pip version:** 22.0.4
- **azure-iot-sdk-version version:** 2.11.0

## Description of the issue

I see this issue crop up now and then. It happens infrequently enough that enabling debug is not sustainable at the moment.

```
Unhandled error while triggering callback for RequestOperation
Unhandled error while triggering callback for MQTTPublishOperation
Unexpected error calling callback for MID: 900
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_ops_base.py", line 138, in complete
    callback(op=self, error=error)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 789, in on_send_request_done
    del self.pending_responses[request_id]
KeyError: '50d56e44-aaaa-bbbb-cccc-87ba8bfe86aa'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_ops_base.py", line 138, in complete
    callback(op=self, error=error)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_ops_base.py", line 196, in on_worker_op_complete
    self.complete(error=error)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_ops_base.py", line 146, in complete
    ) from e
azure.iot.device.common.pipeline.pipeline_exceptions.OperationError: Exception occurred while triggering completion callback

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 664, in cancel_all_operations
    callback(cancelled=True)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 251, in on_complete
    "Operation cancelled before PUBACK received"
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_ops_base.py", line 146, in complete
    ) from e
azure.iot.device.common.pipeline.pipeline_exceptions.OperationError: Exception occurred while triggering completion callback

```

## Code sample exhibiting the issue

```
device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
device_client.on_twin_desired_properties_patch_received = twin_patch_handler
device_client.on_message_received = message_received_handler

while True:
    try:
        device_client.connect()
    finally:
        device_client.disconnect()
```

**Comment by cartertinney** [comment]
Thanks for reporting this, we'll begin looking into it

**Comment by lev-i** [comment]
This is related to the same problem as [994](https://github.com/Azure/azure-iot-sdk-python/issues/994), where multiple downloads of twin data result from on_twin_desired_properties_patch_received. This results in the KeyError seen here, and explains why the code sample reliably reproduces the bug.
