### ISSUE TITLE
Fail to connect by "create_from_connection_string" .

### ISSUE THREAD

**Issue by kamedano** [Azure/azure-iot-sdk-python#1035]
I try to connect to iothub by the following method, but failed in "KeyError: 'DeviceId'"
```
from azure.iot.device.aio import IoTHubDeviceClient
CONNECTION_STRING = "{Connection_String}"
client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)
```

Error message is below
```
Traceback (most recent call last):
  File "C:\xx\IoTHub\sample.py", line 6, in <module>
    client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)
  File "C:\xx\Python\Python39\lib\site-packages\azure\iot\device\aio\patch_documentation.py", line 84, in create_from_connection_string
    return super(IoTHubDeviceClient, cls).create_from_connection_string(
  File "C:\xx\Python\Python39\lib\site-packages\azure\iot\device\iothub\abstract_clients.py", line 287, in create_from_connection_string
    device_id=connection_string[cs.DEVICE_ID],
  File "C:\xx\Python\Python39\lib\site-packages\azure\iot\device\common\auth\connection_string.py", line 90, in __getitem__
    return self._dict[key]
KeyError: 'DeviceId'
```

Refference:
https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.iothubdeviceclient?view=azure-python#azure-iot-device-iothubdeviceclient-create-from-sastoken

**Comment by cartertinney** [comment]
@kamedano

Did you actually replace "{Connection String}" with your connection string? This error indicates your connection string has no device id in it.

**Comment by kamedano** [comment]
I was referring to the wrong ConnectionString
