### ISSUE TITLE
Raspberry pi as iot device can not connect to IoT edge as gateway

### ISSUE THREAD

**Issue by camcuoi** [Azure/azure-iot-sdk-python#1077]
I am trying to send message from Raspberry Pi as iot device to iot hub through linux vm as iot edge gateway . The iot edge gateway uses self signed certificate. Although I have added root CA certificate to iot device, I always get error that it can not verify certificate. Please help advise how I can disable certificate verification.
Code: https://github.com/Azure/azure-iot-sdk-python/blob/main/samples/async-edge-scenarios/send_message_downstream.py 

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/common/mqtt_transport.py", line 396, in connect
    rc = self._mqtt_client.connect(
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
    return await callback.completion()
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 206, in _run_op
    self.transport.connect(password=password)
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/common/mqtt_transport.py", line 409, in connect
    raise exceptions.TlsExchangeAuthError() from e
azure.iot.device.common.transport_exceptions.TlsExchangeAuthError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/connect.py", line 54, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/connect.py", line 35, in main
    await device_client.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/aio/patch_documentation.py", line 14, in connect
    return await super(IoTHubDeviceClient, self).connect()
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 231, in connect
    await handle_result(callback)
  File "/home/pi/.local/lib/python3.9/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 45, in handle_result
    raise exceptions.ClientError("Error in the IoTHub client due to TLS exchanges.") from e
azure.iot.device.exceptions.ClientError: Error in the IoTHub client due to TLS exchanges.
```

**Comment by camcuoi** [comment]
need CA
