### ISSUE TITLE
Running device client on Raspberry Pi

### ISSUE THREAD

**Issue by cartertinney** [Azure/azure-iot-sdk-python#119]
- **OS and version used:** Raspberry Pi 

- **Python runtime used:** 2.7.13 & 2.7.14 (likely others as well) 

- **SDK version used:** Device Client 1.2.2 

# Description of the issue:

Cannot run the samples, runs into an error with the pip package. Seems to be unable to open boost files when importing the package for use.

# Code sample exhibiting the issue:

import iothub_client

# Console log of the issue:

Traceback (most recent call last):
    File "iothub_client_sample.py", line 10, in <module>
        import iothub_client
    File "<PYTHON DIRECTORY>/site-packages/iothub_client/__init__.py", line 1 in <module>
        from .iothub_client_import *
ImportError: libboost_python-py27.so.1.55.0: cannot open shared object file: No such file or directory

**Comment by zolvarga** [comment]
@cartertinney 

Make sure you have the latest pip and setuptools installed in your python environment
sudo pip install -U pip setuptools
 
sudo apt-get install libboost1.55-all
OR
sudo apt-get install libboost-all-dev
OR
sudo apt-get update
sudo apt-get upgrade

Best Regards,
Zoltan
