### ISSUE TITLE
sdk cannot work on python:3.6.5-jessie base image

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-python#131]
- **OS and version used:** use python:3.6.5-jessie base image (for raspberry pi)
- **Python runtime used:** 3.6.5
- **SDK version used:** 1.3.0.0b0

# Description of the issue:
We want to create a arm32v7 edge module to work on raspberry pi. And the base image is python:3.6.5. However, the bits seems has compatible issue and got error:

Traceback (most recent call last):
  File "./filter.py", line 10, in <module>
    import iothub_client
  File "/usr/local/lib/python3.6/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: /usr/local/lib/python3.6/site-packages/iothub_client/iothub_client.so: cannot open shared object file: No such file or director

And we double check the iothub_client.so actually exists under the path specified.

# Code sample exhibiting the issue:
https://github.com/VSChina/iot-edge-python-docker/blob/master/modules/PythonModule/Dockerfile.arm32v7 
https://github.com/VSChina/iot-edge-python-docker/blob/master/modules/PythonModule/filter.py 
https://github.com/VSChina/iot-edge-python-docker/blob/master/modules/PythonModule/requirements.txt 

# Console log of the issue:
  File "./filter.py", line 10, in <module>
    import iothub_client
  File "/usr/local/lib/python3.6/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: /usr/local/lib/python3.6/site-packages/iothub_client/iothub_client.so: cannot open shared object file: No such file or director

**Comment by zolvarga** [comment]
@adashen 

Could you please check if you are using 64 bit OS you are also using 64 Python, and if 32 than 32... 
Please let me know the result.

Best Regards,
Zoltan

**Comment by formulahendry** [comment]
@zolvarga 
Both OS and python are 32 bit
![image](https://user-images.githubusercontent.com/1050213/38909411-1c03ebe4-42f7-11e8-9878-191ddf6d7504.png)

**Comment by pierreca** [comment]
@adashen @formulahendry we released new version of the python packages that support raspbian stretch with v1.4.1 and jessie with version 1.4.0. unfortunately because of our dependency on boost and the way pip works, we can only support one version of raspbian at a time (raspbian can only have one default version of boost against which we build). can you please try with the latest version of the packages and let us know if anything works better?

**Comment by pierreca** [comment]
Closing due to inactivity - feel free to reopen/open a new issue if this isn't solved.

**Comment by az-iot-builder-01** [comment]
@adashen, @formulahendry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Comment by formulahendry** [comment]
Hi @pierreca , I tired but both raspbian stretch and jessie image do not work.. Could you please share your Dockerfile when you do the testing? Thanks a lot!

## **Docker file based on resin/rpi-raspbian:jessie + azure-iothub-device-client==1.4.0**
```
FROM resin/rpi-raspbian:jessie

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python-pip libboost-python-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "bash" ]
```

**Error message in build time:**
```
Step 5/7 : RUN pip install -r requirements.txt
 ---> Running in 05d99f21d3b6
Downloading/unpacking azure-iothub-device-client==1.4.0 (from -r requirements.txt (line 1))
  Could not find any downloads that satisfy the requirement azure-iothub-device-client==1.4.0 (from -r requirements.txt (line 1))
Cleaning up...
No distributions at all found for azure-iothub-device-client==1.4.0 (from -r requirements.txt (line 1))
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```


## **Docker file based on resin/rpi-raspbian:stretch + azure-iothub-device-client==1.4.1**
```
FROM resin/rpi-raspbian:stretch

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python-pip libboost-python-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python", "-u", "./main.py" ]
```
Python code: https://github.com/Azure/cookiecutter-azure-iot-edge-module/blob/master/%7B%7Bcookiecutter.module_name%7D%7D/main.py

**Error message in runtime:**
```
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]

IoT Hub Client for Python
Starting the IoT Hub Python sample using protocol MQTT...
The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit.
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_recv Line:364 executing HTTP request fails, status=404, response_buffer={"message":"Module not found"}d, 01 )
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_error Line:343 on_edge_hsm_http_error invoked.  reason=3
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:send_http_workload_request Line:483 send_request_to_edge_workload failed
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:hsm_client_http_edge_sign_data Line:576 send_http_workload_request failed
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/provisioning_client/src/iothub_auth_client.c Func:iothub_device_auth_generate_credentials Line:339 Failure generate hash from tpm.
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:348 failure getting credentials from device auth module
Error: Time:Wed Aug  1 06:19:53 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1944 failure getting sas token from IoTHubClient_Auth_Get_SasToken.
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_recv Line:364 executing HTTP request fails, status=404, response_buffer={"message":"Module not found"}d, 01 )
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_error Line:343 on_edge_hsm_http_error invoked.  reason=3
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:send_http_workload_request Line:483 send_request_to_edge_workload failed
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:hsm_client_http_edge_sign_data Line:576 send_http_workload_request failed
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/provisioning_client/src/iothub_auth_client.c Func:iothub_device_auth_generate_credentials Line:339 Failure generate hash from tpm.
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:348 failure getting credentials from device auth module
Error: Time:Wed Aug  1 06:19:54 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1944 failure getting sas token from IoTHubClient_Auth_Get_SasToken.
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_recv Line:364 executing HTTP request fails, status=404, response_buffer={"message":"Module not found"}d, 01 )
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_error Line:343 on_edge_hsm_http_error invoked.  reason=3
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:send_http_workload_request Line:483 send_request_to_edge_workload failed
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:hsm_client_http_edge_sign_data Line:576 send_http_workload_request failed
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/provisioning_client/src/iothub_auth_client.c Func:iothub_device_auth_generate_credentials Line:339 Failure generate hash from tpm.
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/iothub_client/src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:348 failure getting credentials from device auth module
Error: Time:Wed Aug  1 06:19:56 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1944 failure getting sas token from IoTHubClient_Auth_Get_SasToken.
Error: Time:Wed Aug  1 06:20:00 2018 File:/usr/sdk/src/c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_recv Line:364 executing HTTP request fails, status=404, response_buffer={"message":"Module not found"}
content-0
```

**Comment by formulahendry** [comment]
Create a new issue #163 to track this.

**Comment by pierreca** [comment]
@formulahendry thanks - creating a new issue was the best way to go - please refrain from describing your problem in multiple places as it unnecessarily weights on our triage process. we look at everything.
