### ISSUE TITLE
Running the service samples behind a proxy

### ISSUE THREAD

**Issue by vanti** [Azure/azure-iot-sdk-python#195]
I tried to run the samples on our company network on a Ubuntu Linux machine behind a proxy server. When I run iothub_messaging_sample.py I get the errors shown below. I have set the http_proxy and ftp_proxy variables, but those do not seem to have any effect over AMQP. Any idea if there is a way to get the sample to work behind a proxy server?

```
> (azureenv) local@udb:~/azure-iot-sdk-python/service/samples$ python iothub_messaging_sample.py -c "HostName=<DELETED>.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<DELETED>" -d devicea5bd950e960539a93a18bea3
> 
> Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
> [GCC 4.8.4]
> IoT Hub Service Client for Python
> 
> Starting the IoT Hub Service Client Messaging Python sample...
>     Connection string = HostName=<DELETED>.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<DELETED>
>     Device ID         = devicea5bd950e960539a93a18bea3
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:282 Failure: getaddrinfo failure -2.
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:765 lookup_address_and_connect_socket failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:saslclientio_open_async Line:1097 xio_open failed
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/uamqp/src/connection.c Func:connection_open Line:1344 Opening the underlying IO failed
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/uamqp/src/link.c Func:link_attach Line:1154 Begin session failed
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/uamqp/src/message_sender.c Func:messagesender_open Line:779 attach link failed
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/iothub_service_client/src/iothub_messaging_ll.c Func:IoTHubMessaging_LL_Open Line:1267 Could not open the message sender.
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/uamqp/src/amqpvalue.c Func:amqpvalue_destroy Line:3465 NULL value
> Error: Time:Fri Sep 14 17:38:07 2018 File:/home/local/workdir/azure/azure-iot-sdk-python/c/uamqp/src/amqpvalue.c Func:amqpvalue_destroy Line:3465 NULL value
> Traceback (most recent call last):
>   File "iothub_messaging_sample.py", line 119, in <module>
>     iothub_messaging_sample_run()
>   File "iothub_messaging_sample.py", line 90, in iothub_messaging_sample_run
>     print ( "Unexpected error {0}" % iothub_error )
> TypeError: not all arguments converted during string formatting
> 
```

[edit/pierreca] Please do not post credentials here. also: please rotate your hub keys asap.
[edit/vanti] No worries. I changed the credentials above before posting. They are not my real ones.

**Comment by vanti** [comment]
Can the service samples use HTTP as opposed to AMQP? It'd make it a lot easier to run them within an internal enterprise network.

**Comment by itslasya** [comment]
when I am running the  script Send a cloud-to-device message following error is comming .
Traceback (most recent call last):
  File "C:/Python27/dtoc.py", line 65, in <module>
    iothub_messaging_sample_run()
  File "C:/Python27/dtoc.py", line 54, in iothub_messaging_sample_run
    print ( "Unexpected error {0}" % iothub_error )
TypeError: not all arguments converted during string formatting

I am using python 2.7 for executing script.
Thanks in Advance

**Comment by pierreca** [comment]
@itslasya I'm not familiar with this error, this seems completely unrelated to this issue and there's not much  info for us to help you in this comment. please open a different github issue and follow the issue template.

@vanti sorry i totally let this issue slip.
This is how a proxy is set up: 
```python
from iothub_client import IoTHubClient, HttpProxyOptions

client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
proxy = HttpProxyOptions("myproxy.com", 8888)
client.set_option("proxy_data", proxy)
```

using a proxy requires using either HTTP (or AMQP over websockets or MQTT Over websockets). Regular TLS socket protocols won't go through an HTTP proxy usually.

**Comment by az-iot-builder-01** [comment]
@vanti, @itslasya, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
