### ISSUE TITLE
Python IOT-Hub-service-client not working with linux Azure application service

### ISSUE THREAD

**Issue by amoljadhavmobiliya** [Azure/azure-iot-sdk-python#284]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Created Azure application service with linux platform
added  python IOT-Hub sample sdk

### Any log messages given by the failure
>

  _____                               
  /  _  \ __________ _________   ____  
 /  /_\  \___   /  |  \_  __ \_/ __ \ 
/    |    \/    /|  |  /|  | \/\  ___/ 
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/ 

A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux

Starting OpenBSD Secure Shell server: sshd.
Site's appCommandLine: gunicorn --bind=0.0.0.0 --timeout 600 --chdir app server:app
Launching oryx with: -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv3.6 -defaultApp /opt/defaultsite -bindPort 8000 -userStartupCommand 'gunicorn --bind=0.0.0.0 --timeout 600 --chdir app server:app'
2019-08-26T13:54:38.015906098Z Oryx Version : 0.2.20190518.2, Commit: 5e1ddd1855bcb53ce686e2124ed6e9603cb0587a
 
 Writing output script to '/opt/startup/startup.sh'
 Using 'oryx-manifest.toml'.
 Checking if virtual environment was compressed...
 Using packages from virtual environment 'antenv3.6' located at '/home/site/wwwroot/antenv3.6'.
 [2019-08-26 13:54:39 +0000] [33] [INFO] Starting gunicorn 19.9.0
 [2019-08-26 13:54:39 +0000] [33] [INFO] Listening at: http://0.0.0.0:8000 (33)
 [2019-08-26 13:54:39 +0000] [33] [INFO] Using worker: sync
 [2019-08-26 13:54:39 +0000] [36] [INFO] Booting worker with pid: 36
 [2019-08-26 13:54:44 +0000] [36] [ERROR] Exception in worker process
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
     worker.init_process()
   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
     self.load_wsgi()
   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
     self.wsgi = self.app.wsgi()
   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
     self.callable = self.load()
   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
     return self.load_wsgiapp()
   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
     return util.import_app(self.app_uri)
   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
     __import__(module)
   File "/home/site/wwwroot/server.py", line 8, in 
     from app import app,config
   File "/home/site/wwwroot/modules/app/__init__.py", line 22, in 
     import iothub_service_client
   File "/home/site/wwwroot/antenv3.6/lib/python3.6/site-packages/iothub_service_client/__init__.py", line 1, in 
     from .iothub_service_client import *
 ImportError: libboost_python-py35.so.1.58.0: cannot open shared object file: No such file or directory
 [2019-08-26 13:54:44 +0000] [36] [INFO] Worker exiting (pid: 36)
 [2019-08-26 13:54:44 +0000] [33] [INFO] Shutting down: Master
 [2019-08-26 13:54:44 +0000] [33] [INFO] Reason: Worker failed to boot.

### Expected/desired behavior
>
Sample application should run with minimum configuration

### OS and Version?
> Azure Linux Application service (which distribution)

### Versions
>
Python 3.7
 Need Support? Every customer with an active Azure subscription has access to [support]

**Comment by pierreca** [comment]
@amoljadhavmobiliya 
yeah that's an issue with the v1 of the SDK that we're in the process of deprecating. you can find details about it here: https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated#important-installation-notes---dealing-with-importerror-issues

We hope to be able to offer a much better service client experience soon (within the next 2 months). in the meantime you'll have to stick to one of the few supported configurations. the team is hard at work trying to solve this problem but for now we've given priority to the device SDK - the service SDK work starts in September.

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@amoljadhavmobiliya, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
