### ISSUE TITLE
Device client drops connection

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python#301]
I'm getting this sporadic error when running SDK-based program on Raspbian. The program suddenly stops sending messages, and this is what I see when breaking the program with Ctrl-C:
`MQTTTransportStage: _on_mqtt_disconnect called: None
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0x75812b90>._execute_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 97, in run_op
    self._execute_op(op)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 139, in _execute_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 331, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.errors.ConnectionDroppedError: The client is not currently connected.
MQTTTransportStage(MQTTPublishOperation): completing with error The client is not currently connected.
IoTHubMQTTConverterStage(SendIotRequestOperation): completing with error The client is not currently connected.
CoordinateRequestAndResponseStage(SendIotRequestAndWaitForResponseOperation): completing with error The client is not currently connected.
HandleTwinOperationsStage(PatchTwinReportedPropertiesOperation): completing with error The client is not currently connected.
Unhandled exception in background thread
This may cause the background thread to abort and may result in system instability.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 113, in thread_proc
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/pipeline/iothub_pipeline.py", line 234, in on_complete
    sys.exit(1)
SystemExit: 1
`

I'm not sure why the device client drops the connection. Is there a way to test the connection status and force reconnect? I checked the list of methods for IoTHubDeviceClient, and so far didn't find anything suitable.

**Comment by BertKleewein** [comment]
Hi @bukarev,

There are a few different answers to your question.  

1. In the short term, I've just pulled https://github.com/Azure/azure-iot-sdk-python/pull/292, which should cause the failure to be returned to your program.  With this change, your call to `patch_twin_reported_properties`  should raise an exception when the connection drops.  When that happens, you should be able to call `patch_twin_reported_properties` and the library should reconnect for you.

2. In the medium term, our library should be automatically reconnecting according to a retry policy that you'll be able to set, and you shouldn't need to worry about manually retrying like this.  This is a feature that is currently under development.

3. This is at least the second request that we've received for testing connection status.  I've opened https://github.com/Azure/azure-iot-sdk-python/issues/303 to address the need for this.

**Comment by bukarev** [comment]
Hi @BertKleewein thanks for your help! is #292 already available via pip, or should I clone this git repo to get that reconnecting behaviour?

**Comment by BertKleewein** [comment]
#292 is not available in via pip yet.  I believe we're aiming for a twice-monthly schedule for releasing to PIP, but I'm not sure about this yet.

**Comment by cartertinney** [comment]
#292 and it's follow up #309 are now both available via pip

**Comment by jebrando** [comment]
@bukarev Thank you for the comment, if you have any more problems with this issue you can reopen this, or you can create a different issue.

Thank you.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @bukarev, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by bukarev** [comment]
@BertKleewein I'm gonna reopen this issue, but maybe I just don't understand how to use what has been improved in the package.
Here's what I'm getting now after I updated the package to the latest version.
`Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0x757b6b50>._execute_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 97, in run_op
    self._execute_op(op)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 142, in _execute_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 404, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: The client is not currently connected.
MQTTTransportStage(MQTTPublishOperation): completing with error The client is not currently connected.
IoTHubMQTTConverterStage(SendIotRequestOperation): completing with error The client is not currently connected.
CoordinateRequestAndResponseStage(SendIotRequestAndWaitForResponseOperation): completing with error The client is not currently connected.
HandleTwinOperationsStage(PatchTwinReportedPropertiesOperation): completing with error The client is not currently connected.
Callback completed with error The client is not currently connected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 97, in run_op
    self._execute_op(op)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 142, in _execute_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 404, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: The client is not currently connected.`

After this the client stops working.

I have something like this in my code:
`try:
    await device_client.patch_twin_reported_properties(rep_prop)
except:
    print('CLIENT DISCONNECTED, RECONNECTING')
    await device_client.patch_twin_reported_properties(rep_prop)`

Have I understood your recommendation right?
