### ISSUE TITLE
Need a way to query connection status

### ISSUE THREAD

**Issue by BertKleewein** [Azure/azure-iot-sdk-python#303]
This has come up in two issues now.  I think we need to add a client API to return connection status to the user.

It was hidden deep inside https://github.com/Azure/azure-iot-sdk-python/issues/148 and less hidden inside https://github.com/Azure/azure-iot-sdk-python/issues/301

**Comment by LouanDuToitS3** [comment]
Hi, any update on this, I am now facing a situation where I can no longer use the V1 client due to a requirement for Python 3.6+, and therefore want to go with the V2 API. My latest tests using preview 13 still has an issue where comms between edge modules start failing silently due to not being connected to edgeHub.

**Comment by BertKleewein** [comment]
I'm pinging the team on this.  In the meantime, are you able to privately share logs with me?  I'm curious to know if I can figure out how it's silently failing.

**Comment by LouanDuToitS3** [comment]
@BertKleewein , will do, give me a couple of days to see what I can get.

**Comment by LouanDuToitS3** [comment]
@BertKleewein , I had a quick search for some of the logs, and below is a small dump of two of the logs. 

Log 1 things remained broken with no connection and no way for me to know there is an error.
Log 2 the connection recovered, and all is well. I still had no knowledge of the issue, but it's fine because it recovered on it's own.

```text
>>>>>>>>>>>>>>>>>>>> Log 1 (Things broken, I have no knowledge of this error, and no connection)
2019-11-25T09:38:18.861468872Z Exception in thread Thread-10:
2019-11-25T09:38:18.861493071Z Traceback (most recent call last):
2019-11-25T09:38:18.861496927Z   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2019-11-25T09:38:18.861500539Z     self.run()
2019-11-25T09:38:18.861512322Z   File "/usr/lib/python3.6/threading.py", line 864, in run
2019-11-25T09:38:18.861515411Z     self._target(*self._args, **self._kwargs)
2019-11-25T09:38:18.861518225Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 3428, in _thread_main
2019-11-25T09:38:18.861521126Z     self.loop_forever(retry_first_connection=True)
2019-11-25T09:38:18.861523861Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1782, in loop_forever
2019-11-25T09:38:18.861526718Z     rc = self.loop(timeout, max_packets)
2019-11-25T09:38:18.861529413Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1177, in loop
2019-11-25T09:38:18.861532293Z     rc = self.loop_read(max_packets)
2019-11-25T09:38:18.861535014Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1568, in loop_read
2019-11-25T09:38:18.861537913Z     rc = self._packet_read()
2019-11-25T09:38:18.861540574Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 2271, in _packet_read
2019-11-25T09:38:18.861543453Z     byte = self._sock_recv(1)
2019-11-25T09:38:18.861546129Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 660, in _sock_recv
2019-11-25T09:38:18.861548991Z     return self._sock.recv(bufsize)
2019-11-25T09:38:18.861551684Z AttributeError: 'NoneType' object has no attribute 'recv'
2019-11-25T09:38:18.861554502Z 
>>>>>>>>>>>>>>>>>>>> Log 2 (All good after error, connection recovers)
2019-11-22T06:23:25.681088998Z ERROR,transport.connect raised error
2019-11-22T06:23:25.685076973Z ERROR,Traceback (most recent call last):
2019-11-22T06:23:25.685092949Z   File "/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/mqtt_transport.py", line 334, in connect
2019-11-22T06:23:25.685097750Z     host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
2019-11-22T06:23:25.685101667Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 937, in connect
2019-11-22T06:23:25.685105675Z     return self.reconnect()
2019-11-22T06:23:25.685109113Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
2019-11-22T06:23:25.685113104Z     sock = self._create_socket_connection()
2019-11-22T06:23:25.685116578Z   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
2019-11-22T06:23:25.685120521Z     return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
2019-11-22T06:23:25.685124069Z   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
2019-11-22T06:23:25.685127794Z     raise err
2019-11-22T06:23:25.685131278Z   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
2019-11-22T06:23:25.685134940Z     sock.connect(sa)
2019-11-22T06:23:25.685149877Z ConnectionRefusedError: [Errno 111] Connection refused
2019-11-22T06:23:25.685152810Z 
2019-11-22T06:23:25.685155269Z The above exception was the direct cause of the following exception:
2019-11-22T06:23:25.685157857Z 
2019-11-22T06:23:25.685160300Z Traceback (most recent call last):
2019-11-22T06:23:25.685162752Z   File "/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 109, in _execute_op
2019-11-22T06:23:25.685167709Z     self.transport.connect(password=self.sas_token)
2019-11-22T06:23:25.685170332Z   File "/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/mqtt_transport.py", line 339, in connect
2019-11-22T06:23:25.685173143Z     raise exceptions.ConnectionFailedError(cause=e)
2019-11-22T06:23:25.685175567Z azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [Errno 111] Connection refused
2019-11-22T06:23:25.685178162Z 
2019-11-22T06:23:25.685508612Z ERROR,MQTTTransportStage(ConnectOperation): completing with error None caused by [Errno 111] Connection refused
2019-11-22T06:23:25.685732628Z WARNING,RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [Errno 111] Connection refused.  Setting timer.
```

**Comment by BertKleewein** [comment]
closing as a duplicate of #401

**Comment by az-iot-builder-01** [comment]
@LouanDuToitS3, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
