### ISSUE TITLE
Linux release script is broken

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#34]
Ubuntu 14.04 LTS
Python 2.7.6
Running on master branch

```
----------------------------------------------------------------------
Ran 31 tests in 0.006s

OK
python2.7 iothub_service_client_map_test.py
test_IoTHubMap (__main__.TestIotHubMap) ... ok
test_IoTHubMapAddDelete (__main__.TestIotHubMap) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.011s

OK
running bdist_wheel
running build
running build_py
copying iothub_client/iothub_client.so -> build/lib.linux-x86_64-2.7/iothub_client
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/azure_iothub_device_client-1.1.14.0.data
creating build/bdist.linux-x86_64/wheel/azure_iothub_device_client-1.1.14.0.data/purelib
creating build/bdist.linux-x86_64/wheel/azure_iothub_device_client-1.1.14.0.data/purelib/iothub_client
copying build/lib.linux-x86_64-2.7/iothub_client/iothub_client.so -> build/bdist.linux-x86_64/wheel/azure_iothub_device_client-1.1.14.0.data/purelib/iothub_client
copying build/lib.linux-x86_64-2.7/iothub_client/__init__.py -> build/bdist.linux-x86_64/wheel/azure_iothub_device_client-1.1.14.0.data/purelib/iothub_client
running install_egg_info
running egg_info
creating azure_iothub_device_client.egg-info
writing azure_iothub_device_client.egg-info/PKG-INFO
writing top-level names to azure_iothub_device_client.egg-info/top_level.txt
writing dependency_links to azure_iothub_device_client.egg-info/dependency_links.txt
writing manifest file 'azure_iothub_device_client.egg-info/SOURCES.txt'
reading manifest file 'azure_iothub_device_client.egg-info/SOURCES.txt'
writing manifest file 'azure_iothub_device_client.egg-info/SOURCES.txt'
Copying azure_iothub_device_client.egg-info to build/bdist.linux-x86_64/wheel/azure_iothub_device_client-1.1.14.0.data/purelib/azure_iothub_device_client-1.1.14.0.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup_device_client.py", line 55, in <module>
    distclass=BinaryDistribution
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 213, in run
    archive_basename = self.get_archive_basename()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 155, in get_tag
    assert tag == supported_tags[0]
AssertionError
running bdist_wheel
running build
running build_py
copying iothub_service_client/iothub_service_client.so -> build/lib.linux-x86_64-2.7/iothub_service_client
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/azure_iothub_service_client-1.1.0.7.data
creating build/bdist.linux-x86_64/wheel/azure_iothub_service_client-1.1.0.7.data/purelib
creating build/bdist.linux-x86_64/wheel/azure_iothub_service_client-1.1.0.7.data/purelib/iothub_service_client
copying build/lib.linux-x86_64-2.7/iothub_service_client/__init__.py -> build/bdist.linux-x86_64/wheel/azure_iothub_service_client-1.1.0.7.data/purelib/iothub_service_client
copying build/lib.linux-x86_64-2.7/iothub_service_client/iothub_service_client.so -> build/bdist.linux-x86_64/wheel/azure_iothub_service_client-1.1.0.7.data/purelib/iothub_service_client
running install_egg_info
running egg_info
creating azure_iothub_service_client.egg-info
writing azure_iothub_service_client.egg-info/PKG-INFO
writing top-level names to azure_iothub_service_client.egg-info/top_level.txt
writing dependency_links to azure_iothub_service_client.egg-info/dependency_links.txt
writing manifest file 'azure_iothub_service_client.egg-info/SOURCES.txt'
reading manifest file 'azure_iothub_service_client.egg-info/SOURCES.txt'
writing manifest file 'azure_iothub_service_client.egg-info/SOURCES.txt'
Copying azure_iothub_service_client.egg-info to build/bdist.linux-x86_64/wheel/azure_iothub_service_client-1.1.0.7.data/purelib/azure_iothub_service_client-1.1.0.7.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup_service_client.py", line 55, in <module>
    distclass=BinaryDistribution
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 213, in run
    archive_basename = self.get_archive_basename()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 155, in get_tag
    assert tag == supported_tags[0]
AssertionError
```

**Comment by bearrito** [comment]
My platform shows the following for wheel 0.29

```
>>> pep425tags.get_supported()
[('cp27', 'cp27mu', 'linux_x86_64'), ('cp27', 'none', 'linux_x86_64'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('cp26', 'none', 'any'), ('cp25', 'none', 'any'), ('cp24', 'none', 'any'), ('cp23', 'none', 'any'), ('cp22', 'none', 'any'), ('cp21', 'none', 'any'), ('cp20', 'none', 'any'), ('py2', 'none', 'linux_x86_64'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
>>> pep425tags.get_impl_ver()
'27'
```

and  for 0.24.0

```
[('cp27', 'none', 'linux_x86_64'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('cp26', 'none', 'any'), ('cp25', 'none', 'any'), ('cp24', 'none', 'any'), ('cp23', 'none', 'any'), ('cp22', 'none', 'any'), ('cp21', 'none', 'any'), ('cp20', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
```

Which would explain the tag assertion fail.

**Comment by bearrito** [comment]
Closing. I was able to get this to work, through some sequence of upgrade to both pip and wheel.
