### ISSUE TITLE
azure-iot-hub not available for pip installation

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python#346]
Just tried to install azure-iot-hub using pip on my Ubuntu:
`sudo pip3 install azure-iot-hub`
error message is as below
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/azure-iot-hub/
```
Most likely it boils down to nothing being available at https://pypi.org/simple/azure-iot-hub/ ?

**Comment by cartertinney** [comment]
The package has not been released yet. We are planning for the first release of azure-iot-hub on October 15th

**Comment by abouroubi** [comment]
Any news on this ?

**Comment by cartertinney** [comment]
The package has been released as of yesterday:

https://pypi.org/project/azure-iot-hub/

**Comment by az-iot-builder-01** [comment]
@bukarev, @abouroubi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abouroubi** [comment]
We still have : "Note that these SDKs are currently in preview, and are subject to change."

What kind of change are expected? 
Can I start the upgrade to this version in my production devices? 
Or will I have to update my code in few weeks because it is not stable
