### ISSUE TITLE
IoTHubRegistryManager.query_iot_hub throws msrest.exceptions.DeserializationError

### ISSUE THREAD

**Issue by capfish** [Azure/azure-iot-sdk-python#423]
Using the azure-iot-hub 2.0.0 on MacOS 10.14.6 with Python 3.6.4 I ran into the above issue details below.

Steps to reproduce:
```
from azure.iot.hub import IoTHubRegistryManager
from azure.iot.hub.protocol.models import QuerySpecification


iotrm = IoTHubRegistryManager(MY_CONNECTION_STRING)
q = QuerySpecification(query="SELECT * FROM devices")
iotrm.query_iot_hub(q)
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/azure/iot/hub/iothub_registry_manager.py", line 488, in query_iot_hub
    return self.protocol.service.query_iot_hub(query_specification)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/azure/iot/hub/protocol/operations/service_operations.py", line 614, in query_iot_hub
    deserialized = self._deserialize("QueryResult", response)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/serialization.py", line 1233, in __call__
    return self._deserialize(target_obj, data)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/serialization.py", line 1303, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/serialization.py", line 1293, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/serialization.py", line 1064, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
```

Expected Result:
A QueryResult containing the devices in the IoTHub.

If I run the following:
```
from azure.iot.hub import IoTHubRegistryManager
from azure.iot.hub.protocol.models import QuerySpecification


iotrm = IoTHubRegistryManager(MY_CONNECTION_STRING)
q = QuerySpecification(query="SELECT * FROM devices")
service = iotrm.protocol.service
url = service.query_iot_hub.metadata["url"]
query_parameters = {}
query_parameters["api-version"] = service._serialize.query("self.api_version", service.api_version, "str")
header_parameters = {}
header_parameters["Accept"] = "application/json"
header_parameters["Content-Type"] = "application/json; charset=utf-8"
body_content = service._serialize.body(q, "QuerySpecification")
request = service._client.post(url, query_parameters, header_parameters, body_content)
response = service._client.send(request, stream=False, **{})
response.status_code
# 200
response.content
# b'[LIST OF DEVICES THAT I EXPECT]'

service._deserialize("QueryResult", response)

Traceback (most recent call last):
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/serialization.py", line 1293, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/Users/cappie/.local/share/virtualenvs/django-api-lC7sxAe1/lib/python3.6/site-packages/msrest/serialization.py", line 1064, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'
```
So something is wrong with the deserializer that the `ServiceOperations` class uses when it is deserializing a "QueryResult"

**Comment by capfish** [comment]
Ah it looks like this [line](https://github.com/Azure/azure-iot-sdk-python/blob/766bb1ac95cee271d278ff49e5b03a9b81a79b20/azure-iot-hub/azure/iot/hub/protocol/operations/service_operations.py#L614) is culprit.  I think it should be
```
deserialized = self._deserialize("[QueryResult]", response)
```
as all queries will return a list.  This gives me the expected output when run manually in a terminal.  It says that the code is auto-generated, I am not quite sure what that means, otherwise I would make a pull request.

**Comment by cartertinney** [comment]
We have replicated and identified the problem, and are working to fix it as soon as possible

**Comment by zolvarga** [comment]
The fix is checked in and it is included in the release v2.0.2 (https://pypi.org/project/azure-iot-hub/)

**Comment by zolvarga** [comment]
Resolved

**Comment by az-iot-builder-01** [comment]
@capfish, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by asayeedi** [comment]
from azure.iot.hub import IoTHubRegistryManager
from azure.iot.hub.protocol.models import QuerySpecification


iotrm = IoTHubRegistryManager(MY_CONNECTION_STRING)
q = QuerySpecification(query="SELECT * FROM devices")
iotrm.query_iot_hub(q)

ERROR:

Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
