### ISSUE TITLE
transport.connect raised error with send_message_to_output.py

### ISSUE THREAD

**Issue by tony979** [Azure/azure-iot-sdk-python#462]
Package https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/sync-samples/send_message_to_output.py to IoT Edge Module, and get the error below:

```
transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/mqtt_transport.py", line 340, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.6/dist-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [Errno 111] Connection refused

ConnectOperation: completing with error None caused by [Errno 111] Connection refused
RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [Errno 111] Connection refused.  Setting timer.
```

**Comment by BertKleewein** [comment]
Hi @tony979, we've been getting quite a few false positives about this error because the SDK is designed to recover from it.  Do you see any other broken functionality besides this exception being logged?

**Comment by tony979** [comment]
Found the root cause. It's similar to https://github.com/Azure/iotedge/issues/9. The sample is working fine with CONFIG_EXT4_FS_SECURITY enabled

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @tony979, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by pospospos2007** [comment]
> Found the root cause. It's similar to [Azure/iotedge#9](https://github.com/Azure/iotedge/issues/9). The sample is working fine with CONFIG_EXT4_FS_SECURITY enabled

Sir how do you enabled CONFIG_EXT4_FS_SECURITY?
