### ISSUE TITLE
'IoTHubRegistryManager' is not defined

### ISSUE THREAD

**Issue by bsafwen** [Azure/azure-iot-sdk-python#48]
- **OS and version used:** <VERSION> 
ubuntu 14.04
- **Python runtime used:** <VERSION> 
python 3.4
- **SDK version used:** <VERSION> 
latest clone

# Description of the issue:

creating a device
# Code sample exhibiting the issue:

```
import random
import time
import sys
import iothub_client
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult
from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue
from iothub_client_args import get_iothub_opt, OptionError

CONNECTION_STRING = "HostName=hubbysafweneful.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=fg6mJq8l2sy28a0e5Td/lHmW5s0Uo0pk9iGU3BgmXmY="
DEVICE_ID = "louel"

def print_device_info(title, iothub_device):
    print ( title + ":" )
    print ( "iothubDevice.deviceId                    = {0}".format(iothub_device.deviceId) )
    print ( "iothubDevice.primaryKey                  = {0}".format(iothub_device.primaryKey) )
    print ( "iothubDevice.secondaryKey                = {0}".format(iothub_device.secondaryKey) )
    print ( "iothubDevice.connectionState             = {0}".format(iothub_device.connectionState) )
    print ( "iothubDevice.status                      = {0}".format(iothub_device.status) )
    print ( "iothubDevice.lastActivityTime            = {0}".format(iothub_device.lastActivityTime) )
    print ( "iothubDevice.cloudToDeviceMessageCount   = {0}".format(iothub_device.cloudToDeviceMessageCount) )
    print ( "iothubDevice.isManaged                   = {0}".format(iothub_device.isManaged) )
    print ( "iothubDevice.authMethod                  = {0}".format(iothub_device.authMethod) )
    print ( "" )

def iothub_createdevice():
    try:
        iothub_registry_manager = IoTHubRegistryManager(CONNECTION_STRING)
        auth_method = IoTHubRegistryManagerAuthMethod.SHARED_PRIVATE_KEY
        new_device = iothub_registry_manager.create_device(DEVICE_ID, "", "", auth_method)
        print_device_info("CreateDevice", new_device)

    except IoTHubError as iothub_error:
        print ( "Unexpected error {0}".format(iothub_error) )
        return
    except KeyboardInterrupt:
        print ( "iothub_createdevice stopped" )


if __name__ == '__main__':
    print ( "" )
    print ( "Python {0}".format(sys.version) )
    print ( "Creating device using the Azure IoT Hub Service SDK for Python" )
    print ( "" )
    print ( "    Connection string = {0}".format(CONNECTION_STRING) )
    print ( "    Device ID         = {0}".format(DEVICE_ID) )

    iothub_createdevice()

```
# Console log of the issue:

```
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4]
Creating device using the Azure IoT Hub Service SDK for Python

    Connection string = HostName=*******
    Device ID         =  **********
Traceback (most recent call last):
  File "p.py", line 47, in <module>
    iothub_createdevice()
  File "p.py", line 27, in iothub_createdevice
    iothub_registry_manager = IoTHubRegistryManager(CONNECTION_STRING)
NameError: name 'IoTHubRegistryManager' is not defined.


```How I set up my environment:
I cloned the repo, run setup.sh but it failed saying "./c/build_all/linux/setup.sh" is not found, I run git submodule update --init to download the contents of the c module and other modules, rerun `./setup.sh --python-version 3.4` ok, run ./`build.sh --build-python 3.4` ok.

**Comment by zolvarga** [comment]
Hi @bsafwen,

Please make sure  after you run build.sh you have **iothub_service_client.so** in the folder where you are running the sample from.

Also you exposed your IoTHub connection string in this conversation. **That is a security issue.** 
There are two things to fix that:
- Change your IoTHub credentials ASAP and start using the new connection string
- Please make sure you won't expose your connection string in the future.

Best Regards,
Zoltan

**Comment by tzot** [comment]
These imports:

    import iothub_client
    from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult
    from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue
    from iothub_client_args import get_iothub_opt, OptionError

do not import the `IoTHubRegistryManager` name in your module.

You should either fix the following line:

    iothub_registry_manager = IoTHubRegistryManager(CONNECTION_STRING)

with:

    iothub_registry_manager = iothub_client.IoTHubRegistryManager(CONNECTION_STRING)

or just include `IoTHubRegistryManager` in one of your `from iothub_client import …` imports.

**Comment by zolvarga** [comment]
@bsafwen,

I don't recognize the code you are using. Could you please point out where is that sample code?
The RegistryManagerSample is here:
https://github.com/Azure/azure-iot-sdk-python/blob/master/service/samples/iothub_registrymanager_sample.py

This sample works just fine.

Please let me know...

Best Regards,
Zoltan

**Comment by tameraw** [comment]
@bsafwen - Closing. Please let us know if still having any issues.
