### ISSUE TITLE
azure-iot-device 2.1.0 random IoTEdgeError causes permanent disconnect from IoT Hub

### ISSUE THREAD

**Issue by samerdokas** [Azure/azure-iot-sdk-python#518]
# Context
- **OS and version used:** Ubuntu 18.04 as host, amd64/python:3.8.2 container
- **Python version:** 3.8.2
- **pip version:** 20.0.2
- **list of installed packages:**
azure-core          1.2.2
azure-iot-device    2.1.0
azure-storage-blob  12.2.0
certifi             2019.11.28
cffi                1.14.0
chardet             3.0.4
coloredlogs         14.0
cryptography        2.8
humanfriendly       8.0
idna                2.9
isodate             0.6.0
janus               0.4.0
msrest              0.6.11
oauthlib            3.1.0
paho-mqtt           1.5.0
pip                 20.0.2
pycparser           2.19
PySocks             1.7.1
requests            2.23.0
requests-oauthlib   1.3.0
requests-unixsocket 0.2.0
setuptools          45.2.0
six                 1.14.0
transitions         0.7.2
urllib3             1.25.8
wheel               0.34.2
- **cloned repo:** No

# Description of the issue:
After an unknown amount of time, an `azure.iot.device.iothub.auth.iotedge_authentication_provider.IoTEdgeError` is raised and it is no longer possible to send telemetry; edgeHub will refuse all attempts with `UnauthorizedError('Connection Refused: not authorised.')`

# Code sample exhibiting the issue:
The initial connection to the IoT Hub is done as follows:
```
result = IoTHubModuleClient.create_from_edge_environment()
result.connect()
```

# Console log of the issue:
Not reliably reproducible, so without debug.
```
2020-03-28 16:50:42,343 - TelemetryReporter[__main__] - INFO - [camera#1] heartbeat events: sent[19] not sent[0]; on[20] off[0] unknown[0] (main.py:97)
2020-03-28 16:50:43,414 - TelemetryReporter[__main__] - INFO - [audio_meter#1] heartbeat events: sent[19] not sent[0]; on[20] off[0] unknown[0] (main.py:97)
Exception in thread Thread-241:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/iothub/auth/iotedge_authentication_provider.py", line 169, in sign
    r.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+unix://%2Fvar%2Frun%2Fiotedge%2Fworkload.sock/modules/sp2-devicelifecyclemanager/genid/637164968329400385/sign?api-version=2019-01-30

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 190, in timerfunc
    this.generate_new_sas_token()
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 127, in generate_new_sas_token
    signature = self._sign(quoted_resource_uri, expiry)
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/iothub/auth/iotedge_authentication_provider.py", line 74, in _sign
    return self.hsm.sign(string_to_sign)
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/iothub/auth/iotedge_authentication_provider.py", line 171, in sign
    raise IoTEdgeError(message="Unable to sign data", cause=e)
azure.iot.device.iothub.auth.iotedge_authentication_provider.IoTEdgeError: IoTEdgeError('Unable to sign data') caused by HTTPError('404 Client Error: Not Found for url: http+unix://%2Fvar%2Frun%2Fiotedge%2Fworkload.sock/modules/sp2-devicelifecyclemanager/genid/637164968329400385/sign?api-version=2019-01-30')
2020-03-28 17:00:44,185 - TelemetryReporter[__main__] - INFO - [camera#1] heartbeat events: sent[17] not sent[0]; on[16] off[0] unknown[0] (main.py:97)
2020-03-28 17:00:44,189 - TelemetryReporter[__main__] - INFO - [audio_meter#1] heartbeat events: sent[17] not sent[0]; on[16] off[0] unknown[0] (main.py:97)
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: UnauthorizedError('Connection Refused: not authorised.')
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: UnauthorizedError('Connection Refused: not authorised.')
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
AutoConnectStage(MQTTPublishOperation): Connection failed.  Completing with failure because of connection failure: UnauthorizedError('Connection Refused: not authorised.')
MQTTPublishOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
SendD2CMessageOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
Callback completed with error UnauthorizedError('Connection Refused: not authorised.')
NoneType: None

ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: UnauthorizedError('Connection Refused: not authorised.')
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
AutoConnectStage(MQTTPublishOperation): Connection failed.  Completing with failure because of connection failure: UnauthorizedError('Connection Refused: not authorised.')
MQTTPublishOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
SendD2CMessageOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
Callback completed with error UnauthorizedError('Connection Refused: not authorised.')
NoneType: None

ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: UnauthorizedError('Connection Refused: not authorised.')
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
AutoConnectStage(MQTTPublishOperation): Connection failed.  Completing with failure because of connection failure: UnauthorizedError('Connection Refused: not authorised.')
MQTTPublishOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
SendD2CMessageOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
Callback completed with error UnauthorizedError('Connection Refused: not authorised.')
NoneType: None

[...]

2020-03-28 17:20:44,302 - TelemetryReporter[__main__] - INFO - [camera#1] heartbeat events: sent[0] not sent[20]; on[20] off[0] unknown[0] (main.py:97)
2020-03-28 17:20:44,302 - TelemetryReporter[__main__] - INFO - [audio_meter#1] heartbeat events: sent[0] not sent[20]; on[20] off[0] unknown[0] (main.py:97)
```

**Comment by BertKleewein** [comment]
This is a 404 talking to iotedged, which is the IoTEdge daemon running on your local machine

```
azure.iot.device.iothub.auth.iotedge_authentication_provider.IoTEdgeError: IoTEdgeError('Unable to sign data') caused by HTTPError('404 Client Error: Not Found for url: http+unix://%2Fvar%2Frun%2Fiotedge%2Fworkload.sock/modules/sp2-devicelifecyclemanager/genid/637164968329400385/sign?api-version=2019-01-30')
```
I would recommend checking to see if the `iotedged` process is still running when this happens.  You can also see the last 200 log entries from this process by using `sudo journalctl -u iotedge -n 200 -e`

**Comment by az-iot-builder-01** [comment]
@samerdokas, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
