### ISSUE TITLE
provision_x509.py

### ISSUE THREAD

**Issue by omersalam** [Azure/azure-iot-sdk-python#552]
i am getting this error while running this sketch 

Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0x7f1982eb7e80>._run_op() call
Traceback (most recent call last):
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 127, in _run_op
    proxy_options=self.pipeline_root.pipeline_configuration.proxy_options,
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 133, in __init__
    self._mqtt_client = self._create_mqtt_client()
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 154, in _create_mqtt_client
    client_id=self._client_id, clean_session=False, protocol=mqtt.MQTTv311
  File "/home/omer/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 555, in __init__
    'A client id must be provided if clean session is False.')
ValueError: A client id must be provided if clean session is False.

SetMQTTConnectionArgsOperation: completing with error A client id must be provided if clean session is False.
SetProvisioningClientConnectionArgsOperation: completing with error A client id must be provided if clean session is False.
SetX509SecurityClientOperation: completing with error A client id must be provided if clean session is False.
Callback completed with error A client id must be provided if clean session is False.
NoneType: None

Traceback (most recent call last):
  File "provision_x509.py", line 39, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "provision_x509.py", line 26, in main
    x509=x509,
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/aio/patch_documentation.py", line 255, in create_from_x509_certificate
    provisioning_host, registration_id, id_scope, x509, **kwargs
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/provisioning/abstract_provisioning_device_client.py", line 144, in create_from_x509_certificate
    security_client, pipeline_configuration
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/provisioning/pipeline/provisioning_pipeline.py", line 132, in __init__
    callback.wait_for_completion()
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
    raise self.exception
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 127, in _run_op
    proxy_options=self.pipeline_root.pipeline_configuration.proxy_options,
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 133, in __init__
    self._mqtt_client = self._create_mqtt_client()
  File "/home/omer/.local/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 154, in _create_mqtt_client
    client_id=self._client_id, clean_session=False, protocol=mqtt.MQTTv311
  File "/home/omer/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 555, in __init__
    'A client id must be provided if clean session is False.')
ValueError: A client id must be provided if clean session is False.
Exception ignored in: <bound method Client.__del__ of <paho.mqtt.client.Client object at 0x7f1982e3f630>>
Traceback (most recent call last):
  File "/home/omer/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 656, in __del__
  File "/home/omer/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 700, in _reset_sockets
  File "/home/omer/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 687, in _sock_close
AttributeError: 'Client' object has no attribute '_sock'

**Comment by stevebus** [comment]
In helping omer - I get the same error as above...
- I created a root and device cert using the ./certGen.sh script from the SDK
- uploaded the root cert to DPS and went successfully through the verification process
- set the environment variables  (I changed a random character in my IDScope below to not leak my real scope ehre
declare -x PROVISIONING_HOST="http://global.azure-devices-provisioning.net"
declare -x PROVISIONING_IDSCOPE="0ne00022505"
declare -x PROVISIONING_REGISTRATION_ID="omertestdevice1"
declare -x X509_CERT_FILE="/home/stevebus/edge/certs/iot-device-omertestdevice1-full-chain.cert.pem"
declare -x X509_KEY_FILE="/home/stevebus/edge/private/iot-device-omertestdevice1.key.pem"

the x509_PASS_PHRASE is empty because my private key doesn't have a pass phrase..

so when I run python3 provisioning_x509.py, I get the same error @omersalam got above...

below is the CN of my cert to confirm
        Validity
            Not Before: Apr 27 18:36:36 2020 GMT
            Not After : May 27 18:36:36 2020 GMT
        Subject: CN=omertestdevice1
        Subject Public Key Info:

**Comment by stevebus** [comment]
FYI - got this to work by removing the environment variables and hard-coding the values in the script..  somewhere the env var values are getting lost

(I also realized that the provisioning host does not need 'http://' on the front of it  (i.e. just 'global.azure-devices-provisioning.net')

**Comment by olivakar** [comment]
@omersalam did the above fix your issue ?
Can this issue be closed then ?

**Comment by reppners** [comment]
In case of executing in the shell don't forget to `export` the variable, e.g. `export PROVISIONING_HOST="global.azure-devices-provisioning.net"`

**Comment by stevebus** [comment]
Not sure if he'll respond here, but I've been corresponding with omer separately and he got this to work.

**Comment by az-iot-builder-01** [comment]
@omersalam, @stevebus, @reppners, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
