### ISSUE TITLE
Raspberry Pi Zero - Fails to connect.

### ISSUE THREAD

**Issue by DonkDH** [Azure/azure-iot-sdk-python#561]
# Context
Hardware: Running on a Raspberry Pi Zero W
OS: Raspbian Buster
Python Version: 3.7.3
Pip: 18.1
pip3 list
Package             Version
------------------- ---------
asn1crypto          0.24.0
azure-iot-device    2.1.0
certifi             2018.8.24
chardet             3.0.4
cryptography        2.6.1
entrypoints         0.3
idna                2.6
janus               0.5.0
keyring             17.1.1
keyrings.alt        3.1.1
paho-mqtt           1.5.0
pip                 18.1
pycrypto            2.6.1
PyGObject           3.30.4
PySocks             1.7.1
python-apt          1.8.4.1
pyxdg               0.25
requests            2.21.0
requests-unixsocket 0.2.0
SecretStorage       2.3.1
setuptools          40.8.0
six                 1.12.0
ssh-import-id       5.7
transitions         0.8.1
urllib3             1.24.1
wheel               0.32.3

Running the sample described here: https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples I get the following error message:
This was after starting from a clean install of Rasbian.

 python3 test.py
`transport.connect raised error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 367, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 117, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 387, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')

ConnectOperation: completing with error ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')
ConnectOperation: completing with error ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')
Callback completed with error ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')
["azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')\n"]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 367, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 30, in handle_result
    return await callback.completion()
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
    return await self.future
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 117, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 387, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by OSError(101, 'Network is unreachable')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 14, in main
    await device_client.connect()
  File "<string>", line 1, in connect
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 108, in connect
    await handle_result(callback)
  File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 34, in handle_result
    raise exceptions.ConnectionFailedError(message="Could not connect to IoTHub", cause=e)
azure.iot.device.exceptions.ConnectionFailedError: ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)`

**Comment by jebrando** [comment]
@DonkDH It looks from the message that the device doesn't have a connection to the internet.  Is the wireless connection on the board working?

**Comment by DonkDH** [comment]
I am able to sucessufully ping google.com and install new python SDKs with pip3 while I get this error. So it seems the internet is working, is there any ports I need to open on my router or something along those lines?

**Comment by olivakar** [comment]
can u check for port 8883 ?

**Comment by DonkDH** [comment]
I have set a port forwarding rule on my router and installed 'Uncomplicated Fire Wall' on the pi and set the port 8883 to be open. 
But I am getting the same error message from the sample code. 

Although I'm not sure how I can check that the fire wall settings are correct and the port forward has worked.

**Comment by olivakar** [comment]
can u ping your pi from some other machine ?

**Comment by DonkDH** [comment]
I can ping it from my windows machine although I am not sure how to do that though a specific port.

**Comment by DonkDH** [comment]
Quick update on my situation, I managed to resolve my problem. 
It was a misteak I'd made when setting up a static IP on my Raspberry Pi, that somehow resulted in me being able to do most internet related things but not use this library or another python library called Requests. 

Thank you for your time and suggestions.

**Comment by az-iot-builder-01** [comment]
@DonkDH, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by nalinabrol** [comment]
> Quick update on my situation, I managed to resolve my problem. It was a misteak I'd made when setting up a static IP on my Raspberry Pi, that somehow resulted in me being able to do most internet related things but not use this library or another python library called Requests.
> 
> Thank you for your time and suggestions.

How did you setup the static IP on your Rasphberry Pi
