### ISSUE TITLE
Cloud to device message causes index out of bound exception

### ISSUE THREAD

**Issue by cima** [Azure/azure-iot-sdk-python#575]
At [line 291 of mqtt_topic_iothub.py](https://github.com/Azure/azure-iot-sdk-python/blob/deadeab184c52ec848b306aa20dc39cc9e69ef0e/azure-iot-device/azure/iot/device/iothub/pipeline/mqtt_topic_iothub.py#L291) is direct access to second list item without any check or default return value approach which causes python to raise followin exception:

```
Unexpected error in <azure.iot.device.iothub.pipeline.pipeline_stages_iothub_mqtt.IoTHubMQTTTranslationStage object at 0x00000271AD6881C8>._handle_pipeline_event() call
Traceback (most recent call last):
  File "C:\Users\z608328\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\iot\device\common\pipeline\pipeline_stages_base.py", line 136, in handle_pipeline_event
    self._handle_pipeline_event(event)
  File "C:\Users\z608328\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\iot\device\common\pipeline\pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\z608328\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\iot\device\iothub\pipeline\pipeline_stages_iothub_mqtt.py", line 225, in _handle_pipeline_event
    mqtt_topic_iothub.extract_message_properties_from_topic(topic, message)
  File "C:\Users\z608328\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\iot\device\iothub\pipeline\mqtt_topic_iothub.py", line 291, in extract_message_properties_from_topic
    value = urllib.parse.unquote(pair[1])
IndexError: list index out of range

Exception caught in background thread.  Unable to handle.
```
As the input (properties) of this method is external it should never be expected that it will be well formated.

# Steps to reproduce
1. Use sample [receive_message.py](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/receive_message.py)
  * Python 3.7.6 64 bit
  * azure-iot-device 2.1.2
2. Create & send cloud to device message which will contain peorperties without value as shown bellow. **Note the single `className` without `=something`.**
```
%24.to=%2Fdevices%2Fgitlabplatformagent%2Fmessages%2Fdevicebound&serialization=json&UserName=Z608328&clientId=15869841-7ae2-46e2-b5b5-cc4719ebdb98&assetId=18df6ae6-f271-4d09-ab22-a917d1918a3f&name=com.openmatics.dashboard.realtimedataservice.RealTimeDataMessage&PartitionKey=1&correlationId=ckapmd1q4056401744c0m40ra&className&PartitionId=0&iothub-ack=full&mdReceived=2020-05-27T17%3A25%3A19.996
```
![python-non-tuples](https://user-images.githubusercontent.com/4488941/83055196-cd944f00-a053-11ea-95a2-3ebafa26c819.png)
3. see output of the example 

## Expected output
Brief description of the C2D message

## Actual output
Above mentioned exception

AB#7366711

**Comment by cartertinney** [comment]
We are looking into this issue and will respond once we validate this scenario with the Azure IoT Hub

**Comment by cartertinney** [comment]
@cima could you clarify how it was that you were able to send a C2D message with a custom property that has a key but no value? Azure CLI? IoT Explorer? Something else?

**Comment by cima** [comment]
I was affraid this question will appear. Unfortunately it is the project I cannot share and I even dont want to becuase it is ugly code of crazy service I am replacing and thus when testing compatibility I have experience the value-less property issue.

Anyway it was fairly easy to pick the lines of the code and quickly sketch below **JUnit test** that sends cloud-to-device message with value-less property and voila it again ended up with the python exception.

```java
package cz.cima.iothub;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

import com.google.common.base.Charsets;
import com.microsoft.azure.sdk.iot.service.IotHubServiceClientProtocol;
import com.microsoft.azure.sdk.iot.service.Message;
import com.microsoft.azure.sdk.iot.service.ServiceClient;
import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;

public class ValueLessPropertyTest {
	
	private String connectionString = "<TODO>";
	private static String DEVICE_ID = "gitlabplatformagent";
	
	@Test
	public void sendC2DWithValuelessProperty() throws IOException, IotHubException {
		Map<String,String> properties = new HashMap<>();
        properties.put("deviceId", DEVICE_ID);
        
        byte[] payload = "Gizmo likes pizza".getBytes(Charsets.UTF_8);
        
        properties.put("className", null);

        ServiceClient iotServiceClient = ServiceClient.createFromConnectionString(connectionString, IotHubServiceClientProtocol.AMQPS);
        
        Message message = new Message(payload);
        message.setProperties(properties);
        
        iotServiceClient.open();
        iotServiceClient.send(DEVICE_ID, message);
        iotServiceClient.close();
	}

}
```

**Comment by cartertinney** [comment]
Thank you, this is very helpful. Lastly, could you explain your motive for doing this?

Are you trying to send a property with no value (i.e. className), or a property that is set to null/None (i.e. className=None)

**Comment by cima** [comment]
There is no intention to do it. It is definitely a bug in the running version of our ancient service because in the head of our repository there is not even the code doing this (Somebody probably fixed it in unreleased version). However as it is possible and apparently permitted by MQTT & AMQP protocols the receivers should expect value-less properties.

**Comment by cartertinney** [comment]
The reason I ask is because it seems there is inconsistency on how this is handled across different service clients. I'm trying to get to the bottom of the problem, but, it's relevant for me to understand what you expect this to do:

What do you expect to receive on this message? className having A null/None value? i.e. className=None, or are you not even expecting that, and just expecting the key with no associated value (i.e. not even the null/None)

**Comment by cima** [comment]
We have had no intention to send that property empty/null/none. It was purely a bug that the variable used to set the _className_ propery contained null. It just wasn't sanitized.

I think that the behavior and semantics of value-less property should be specified within the AMQP/MQTT RFCs.

**Comment by cima** [comment]
There is no intention to do it. It is definitely a bug in the running version of our ancient service because in the head of our repository there is not even the code doing this (Somebody probably fixed it in unreleased version). However as it is possible and apparently permitted by MQTT & AMQP protocols the receivers should expect value-less properties.

**Comment by luisgizirian** [comment]
We're experiencing something similar. In our case, it's a message flowing thru MQTT infrastructure from a module to another in an IoT Edge Device scenario. The exception raises upon message reception on the destination module.

* MQTT connectivity is working
`During initialization`
```
2020-06-11 15:37:19,410 azure.iot.device.iothub.aio.async_clients INFO  Enabling feature:input...
2020-06-11 15:37:19,411 azure.iot.device.iothub.pipeline.mqtt_pipeline DEBUG enable_feature input called
2020-06-11 15:37:19,412 azure.iot.device.iothub.aio.async_clients INFO  Enabling feature:twin_patches...
2020-06-11 15:37:19,412 azure.iot.device.common.pipeline.pipeline_thread DEBUG Starting run_op in pipeline thread
2020-06-11 15:37:19,416 azure.iot.device.iothub.pipeline.mqtt_pipeline DEBUG enable_feature twin_patches called
2020-06-11 15:37:19,417 azure.iot.device.common.pipeline.pipeline_ops_base DEBUG EnableFeatureOperation: creating worker op of type MQTTSubscribeOperation
2020-06-11 15:37:19,418 azure.iot.device.common.pipeline.pipeline_thread DEBUG Starting run_op in pipeline thread
2020-06-11 15:37:19,419 azure.iot.device.common.pipeline.pipeline_stages_base INFO  AutoConnectStage(MQTTSubscribeOperation): Connected.  Sending down and adding callback to check result
2020-06-11 15:37:19,421 azure.iot.device.common.pipeline.pipeline_stages_base DEBUG OpTimeoutStage(MQTTSubscribeOperation): Creating timer
2020-06-11 15:37:19,422 azure.iot.device.common.pipeline.pipeline_stages_base DEBUG OpTimeoutStage(MQTTSubscribeOperation): Sending down
2020-06-11 15:37:19,422 azure.iot.device.common.pipeline.pipeline_stages_mqtt INFO  MQTTTransportStage(MQTTSubscribeOperation): subscribing to devices/someDevice/modules/objectCounter/inputs/#
2020-06-11 15:37:19,423 azure.iot.device.common.mqtt_transport INFO  subscribing to devices/someDevice/modules/objectCounter/inputs/# with qos 1
2020-06-11 15:37:19,423 paho                 DEBUG Sending SUBSCRIBE (d0, m1) [(b'devices/someDevice/modules/objectCounter/inputs/#', 1)]
2020-06-11 15:37:19,423 azure.iot.device.common.mqtt_transport DEBUG _mqtt_client.subscribe returned rc=0
2020-06-11 15:37:19,426 azure.iot.device.common.mqtt_transport DEBUG Waiting for response on MID: 1
2020-06-11 15:37:19,427 azure.iot.device.iothub.pipeline.pipeline_stages_iothub INFO  EnsureDesiredPropertiesStage: enabling twin patches.  setting last_version_seen
2020-06-11 15:37:19,427 paho                 DEBUG Received SUBACK
2020-06-11 15:37:19,428 azure.iot.device.common.mqtt_transport INFO  suback received for 1
2020-06-11 15:37:19,429 azure.iot.device.common.mqtt_transport DEBUG Response received for recognized MID: 1 - triggering callback
```
* Tryed with Python 3.7 and 3.8
* Azure Iot Device: 2.1.2 (https://pypi.org/project/azure-iot-device/2.1.2/)

The exception:
```
Unexpected error in <azure.iot.device.iothub.pipeline.pipeline_stages_iothub_mqtt.IoTHubMQTTTranslationStage object at 0x7fbe52442350>._handle_pipeline_event() call Traceback (most recent call last): 
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 132, in handle_pipeline_event     self._handle_pipeline_event(event)   
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper     return func(*args, **kwargs)   
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/pipeline_stages_iothub_mqtt.py", line 225, in _handle_pipeline_event     mqtt_topic_iothub.extract_properties_from_topic(topic, message)   
File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/mqtt_topic_iothub.py", line 194, in extract_properties_from_topic     value = urllib.parse.unquote_plus(pair[1]) IndexError: list index out of range Exception caught in background thread.  Unable to handle. ['IndexError: list index out of range\n']
```
With Logging (DEBUG):
```
2020-06-11 15:44:41,071 azure.iot.device.common.mqtt_transport INFO  message received on devices/some-device/modules/objectCounter/inputs/detectedObjects/topic=%2Fsubscriptions%2F00000000-0000-0000-0000-cf350e31ee68%2FresourceGroups%2Fsome-rg%2Fproviders%2Fmicrosoft.media%2Fmediaservices%2Fsomemediaservice&subject=%2FgraphInstances%2FSample-Graph-1%2Fprocessors%2FinferenceClient&eventType=Microsoft.Media.Graph.Analytics.Inference&eventTime=2020-06-11T15%3A44%3A40.388Z&dataVersion=1.0&%24.cdid=some-device&%24.cmid=someModule&%24.mid=add94084-0000-0000-0000-960d02ce4f1a&%24.cid
2020-06-11 15:44:41,071 azure.iot.device.common.pipeline.pipeline_thread DEBUG Starting _on_mqtt_message_received in pipeline thread
2020-06-11 15:44:41,072 azure.iot.device.common.pipeline.pipeline_stages_mqtt DEBUG MQTTTransportStage: message received on topic devices/some-device/modules/objectCounter/inputs/detectedObjects/topic=%2Fsubscriptions%2F00000000-0000-0000-0000-cf350e31ee68%2FresourceGroups%2Fsome-rg%2Fproviders%2Fmicrosoft.media%2Fmediaservices%2Fsomemediaservice&subject=%2FgraphInstances%2FSample-Graph-1%2Fprocessors%2FinferenceClient&eventType=Microsoft.Media.Graph.Analytics.Inference&eventTime=2020-06-11T15%3A44%3A40.388Z&dataVersion=1.0&%24.cdid=some-device&%24.cmid=origModule&%24.mid=add94084-0000-0000-0000-960d02ce4f1a&%24.cid
2020-06-11 15:44:41,072 azure.iot.device.common.pipeline.pipeline_stages_base ERROR Unexpected error in <azure.iot.device.iothub.pipeline.pipeline_stages_iothub_mqtt.IoTHubMQTTTranslationStage object at 0x7f04ab1d8dd0>._handle_pipeline_event() call
2020-06-11 15:44:41,074 azure.iot.device.common.pipeline.pipeline_stages_base ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 136, in handle_pipeline_event
    self._handle_pipeline_event(event)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/pipeline_stages_iothub_mqtt.py", line 230, in _handle_pipeline_event
    mqtt_topic_iothub.extract_message_properties_from_topic(topic, message)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/mqtt_topic_iothub.py", line 291, in extract_message_properties_from_topic
    value = urllib.parse.unquote(pair[1])
IndexError: list index out of range
```

**Comment by olivakar** [comment]
@luisgizirian  Could you please elaborate on how you are able to create the the situation where the system property `correlation id` is having no value  ?

**Comment by Sanjidhalim** [comment]
Hi @olivakar, the message that @luisgizirian  was referring to was created using the C# SDK. I have included a sample below. We are using version 1.29.0-preview-004 of the Microsoft.Azure.Devices.Client dll. CorrelationId on the event message is a nullable Guid. In this case, the message is generated on an IoT Edge Module running on a Edge device.

Even though from the code it looks like I am just setting a string, it looks like the SDK is populating a key (`correlation-id`) in a dictionary with a null value. 

```c#

using Microsoft.Azure.Devices.Client;

    var iotMessage = new Message();

    // Assign system properties
    iotMessage.MessageId = eventMessage.Id.ToString();
    iotMessage.CorrelationId = eventMessage.CorrelationId?.ToString();
```

The strange this is if the messages are routed upstream from the edge module and the Event Hub associated with the IoT Hub is monitored (using Event Hub C# SDK or the IoT Edge VS Code extension), the system properties do not include correlation ID. However when the messages are routed to another edge module we see the error above.

**Comment by az-iot-builder-01** [comment]
@cima, @luisgizirian, @Sanjidhalim, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
