### ISSUE TITLE
Unable to connect from inside azure container instance. 

### ISSUE THREAD

**Issue by arnabhetc** [Azure/azure-iot-sdk-python#626]
We have a simulator solution, which is an IoT device that sends JSON data to IoT hub in some interval, it using the python3 and azure-iot-device library  

- whatever our codebase is is running fine locally in windows, MAC and Ubuntu 

- whenever it's being deployed to azure container and running from the azure container instance, in the log the bellow error is coming 

```
Starting initialization of Client . . . 
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: UnauthorizedError('Connection Refused: not authorised.')
ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
Callback completed with error UnauthorizedError('Connection Refused: not authorised.')
NoneType: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 32, in handle_result
    return callback.wait_for_completion()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
    raise self.exception
azure.iot.device.common.transport_exceptions.UnauthorizedError: UnauthorizedError('Connection Refused: not authorised.')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "./main.py", line 279, in <module>
    redbird_init()
  File "./main.py", line 271, in redbird_init
    device_one = main(config["sample_device_1"])
  File "./main.py", line 41, in __init__
    self.iothub.iothubclient_init()
  File "/app/SendEvent.py", line 31, in iothubclient_init
    self.iothubdeviceClient.connect()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/patch_documentation.py", line 14, in connect
    return super(IoTHubDeviceClient, self).connect()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 116, in connect
    handle_result(callback)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 38, in handle_result
    raise exceptions.CredentialError(message="Credentials invalid, could not connect", cause=e)
azure.iot.device.exceptions.CredentialError: CredentialError('Credentials invalid, could not connect') caused by UnauthorizedError('Connection Refused: not authorised.')
```
it coming while connecting to the client, but the same problem is not coming using the same connection string when running locally. 

The content of the docker file is -->

```
FROM python:alpine3.7
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
CMD python ./main.py
```
requirements.txt  contains  `azure-iot-device`

AB#7723492

**Comment by az-iot-builder-01** [comment]
@arnabhetc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Austout** [comment]
Any update on this as I'm having a near-identical issue?

**Comment by milindyadav01** [comment]
How was this solved any update on this? Facing same issue here.
