### ISSUE TITLE
IoTHubModuleClient keeps reseting connection with edgeHubDev

### ISSUE THREAD

**Issue by fbrandao** [Azure/azure-iot-sdk-python#634]
Hello all,

# Context 
OS and version used: Ubuntu 18.04 LTS
Python version: 3.6

# Description
I have a IoT Edge Solution that has 2 modules in it. While running everything locally on my host machine everything works correctly, i do the iotedgehubdev setup using a connection string to an edge device, and then bring all the modules up using "Run IoT Edge Solution in Simulator".

I am beginning to develop a tool that will use the IoTHubModuleClient class, and it will connect to the current running solution and given a module input it will listen to the incoming messages to that input.
I am using the sample from https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-edge-scenarios/receive_message_on_input.py as a baseline to start my work but i am facing some issues.

# The problems
When i start the above sample pointing to a specific module input, i immediately the following errors appearing in the so far normally working modules.
I am using the create_from_edge_environment() method to create the module client, i also have tried with connection string and certificate  and the results were the same.

**Module that i am connecting to logs**  - This proceeds repeats itself infinitely until i stop my sampler:

`Connection Status: Connected
16:04:16.017 [MQTT Rec: ] WARN  com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt - Mqtt connection lost
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) [app.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.8.0_212]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[app.jar:?]
	... 1 more
16:04:16.025 [azure-iot-sdk-ReconnectionTask:3c8d8293-bf6e-4ffc-92b6-5e0fa59e6e48] INFO  com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Handling a disconnection event
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75) ~[app.jar:?]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:389) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[app.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.8.0_212]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[app.jar:?]
	... 1 more
16:04:16.026 [azure-iot-sdk-ReconnectionTask:3c8d8293-bf6e-4ffc-92b6-5e0fa59e6e48] WARN  com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75) ~[app.jar:?]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:389) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) ~[app.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.8.0_212]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[app.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[app.jar:?]
	... 1 more
Connection Status: Retrying`

**edgeHubDev container logs:**
`<6> 2020-07-24 07:50:56.842 +00:00 [INF] - Bind device proxy for device EDGE-DEVICE/MODULE-NAME
<6> 2020-07-24 07:50:56.842 +00:00 [INF] - Binding message channel for device Id EDGE-DEVICE/MODULE-NAME
<6> 2020-07-24 07:50:57.374 +00:00 [INF] - Client EDGE-DEVICE/MODULE-NAME in device scope authenticated locally.
<6> 2020-07-24 07:50:57.374 +00:00 [INF] - Successfully generated identity for clientId EDGE-DEVICE/MODULE-NAME and username cloud-platform-iot-hub.azure-devices.net/EDGE-DEVICE/MODULE-NAME/?api-version=2019-10-01&DeviceClientType=com.microsoft.azure.sdk.iot.iot-device-client%2F1.23.0%20%281.8.0_212%3B%20Linux%3B%20amd64%29
<6> 2020-07-24 07:50:57.374 +00:00 [INF] - ClientAuthenticated, EDGE-DEVICE/MODULE-NAME, 38a6bf1e
<6> 2020-07-24 07:50:57.375 +00:00 [INF] - New device connection for device EDGE-DEVICE/MODULE-NAME
<4> 2020-07-24 07:50:57.375 +00:00 [WRN] - Closing connection for device: EDGE-DEVICE/MODULE-NAME, Microsoft.Azure.Devices.Edge.Hub.Core.MultipleConnectionsException: Multiple connections detected for device EDGE-DEVICE/MODULE-NAME, 
<6> 2020-07-24 07:50:57.375 +00:00 [INF] - Disposing MessagingServiceClient for device Id EDGE-DEVICE/MODULE-NAME because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.MultipleConnectionsException: Multiple connections detected for device EDGE-DEVICE/MODULE-NAME
<6> 2020-07-24 07:50:57.375 +00:00 [INF] - Closing device proxy for device Id EDGE-DEVICE/MODULE-NAME`

# Questions

Has this issue been experienced in the past by anyone?
Although this connection resets occur, i am still able to receive the messages on the desired inputs. Is this the expected behaviour?
Does that sample code need improvement to include this situation?
What other steps do you suggest i could try to overcome or progress on this issue?

AB#7791898

**Comment by jebrando** [comment]
@fbrandao The logs you pasted are Java specific logs.  Do you have the Python logs for this error?

**Comment by elhorton** [comment]
Hi @fbrandao , due to lack of response we are going to close this issue for now. If this is still an issue, please reopen with Python logs

**Comment by az-iot-builder-01** [comment]
@fbrandao, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
