### ISSUE TITLE
IoTHubModuleClient fails to re-authenticate with edgeHub

### ISSUE THREAD

**Issue by ryayl** [Azure/azure-iot-sdk-python#638]
# Context

System: ARM32 with Yocto based Linux
Edge Daemon: v1.0.5 running in a Debian container (see https://github.com/VMinute/torizon-azure-iot-edge)
Edge Agent/Hub: v1.0.94.32971639
Python: 3.7.7
azure-iot-device: 2.1.4

## Description of the Issue

I have an IoT Edge Solution with several continuously running modules. One module is the Microsoft-provided azure-blob-storage aka azureblobstorageoniotedge (let's call it ABS). My custom Module A uses the C++ SDK, while custom Module B uses the Python SDK. Both A and B generate blob data, which is sent to ABS and eventually uploaded to our cloud. The uplink is over a cellular modem and network outages are expected. During network instability it seems like both Module A and ABS recover, while Module B using the Python SDK sometimes gets disconnected from edgeHub following an authentication error. I have to restart Module B to recover. In the example below everything came up and ran successfully for over an hour before the error.

**EdgeHub log** shows that periodically, modules are asked to re-authenticate:

Module B fails authentication and ends up in the state "is not connected":

```
<6> 2020-07-30 06:07:01.111 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-07-30 06:07:01.128 +00:00 [INF] - Error authenticating token for Delta/ModuleB because the token is expired or could not be parsed
<6> 2020-07-30 06:07:01.128 +00:00 [INF] - Credentials for client Delta/ModuleB are not valid.
<4> 2020-07-30 06:07:01.129 +00:00 [WRN] - Reauthenticating client Delta/ModuleB failed, removing client connection
<6> 2020-07-30 06:07:01.129 +00:00 [INF] - Unable to re-authenticate Delta/ModuleB, dropping client connection.
<6> 2020-07-30 06:07:01.130 +00:00 [INF] - Removing device connection for device Delta/ModuleB with removeCloudConnection flag 'True'.
<4> 2020-07-30 06:07:01.131 +00:00 [WRN] - Closing connection for device: Delta/ModuleB, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device Delta/ModuleB., 
<6> 2020-07-30 06:07:01.131 +00:00 [INF] - Disposing MessagingServiceClient for device Id Delta/ModuleB because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device Delta/ModuleB.
<6> 2020-07-30 06:07:01.133 +00:00 [INF] - Closing device proxy for device Id Delta/ModuleB
<6> 2020-07-30 06:07:01.134 +00:00 [INF] - Device connection removed for device Delta/ModuleB
<6> 2020-07-30 06:07:01.536 +00:00 [INF] - Error authenticating token for Delta/ModuleB because the token is expired or could not be parsed
<6> 2020-07-30 06:07:01.537 +00:00 [INF] - Credentials for client Delta/ModuleB are not valid.
<6> 2020-07-30 06:07:01.538 +00:00 [INF] - Client Delta/ModuleB in device scope not authenticated locally.
<3> 2020-07-30 06:07:01.555 +00:00 [ERR] - Unable to generate identity for clientId Delta/ModuleB and username mss-prod.azure-devices.net/Delta/ModuleB/?api-version=2019-10-01&DeviceClientType=azure-iot-device-iothub-py%2F2.1.4%283.7.6%3BLinux%20%231%20SMP%20Tue%20Nov%2012%2012%3A57%3A30%20UTC%202019%3Barmv7l%29
<6> 2020-07-30 06:07:01.557 +00:00 [INF] - ClientNotAuthenticated, Client ID: Delta/ModuleB; Username: mss-prod.azure-devices.net/Delta/ModuleB/?api-version=2019-10-01&DeviceClientType=azure-iot-device-iothub-py%2F2.1.4%283.7.6%3BLinux%20%231%20SMP%20Tue%20Nov%2012%2012%3A57%3A30%20UTC%202019%3Barmv7l%29, 4561e1df
<4> 2020-07-30 06:07:46.360 +00:00 [WRN] - Module Delta/ModuleB is not connected
```

ABS also fails authentication but never reports "ClientNotAuthenticated":

```
<6> 2020-07-30 06:17:01.110 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-07-30 06:17:01.112 +00:00 [INF] - Error authenticating token for Delta/azureblobstorageoniotedge because the token is expired or could not be parsed
<6> 2020-07-30 06:17:01.113 +00:00 [INF] - Credentials for client Delta/azureblobstorageoniotedge are not valid.
<4> 2020-07-30 06:17:01.114 +00:00 [WRN] - Reauthenticating client Delta/azureblobstorageoniotedge failed, removing client connection
<6> 2020-07-30 06:17:01.114 +00:00 [INF] - Unable to re-authenticate Delta/azureblobstorageoniotedge, dropping client connection.
<6> 2020-07-30 06:17:01.115 +00:00 [INF] - Removing device connection for device Delta/azureblobstorageoniotedge with removeCloudConnection flag 'True'.
<4> 2020-07-30 06:17:01.115 +00:00 [WRN] - Closing connection for device: Delta/azureblobstorageoniotedge, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device Delta/azureblobstorageoniotedge., 
<6> 2020-07-30 06:17:01.139 +00:00 [INF] - Disposing MessagingServiceClient for device Id Delta/azureblobstorageoniotedge because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device Delta/azureblobstorageoniotedge.
<6> 2020-07-30 06:17:01.139 +00:00 [INF] - Closing device proxy for device Id Delta/azureblobstorageoniotedge
<6> 2020-07-30 06:17:01.140 +00:00 [INF] - Device connection removed for device Delta/azureblobstorageoniotedge
```

After this error, Module A continues sending data to the cloud through ABS, but Module B can no longer communicate with the hub. At the time of the failed re-authentication, here is the error reported in the **Module B log**:

```
07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: disconnected with result code: 1
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport:   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 626, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1782, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1177, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1570, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2230, in _loop_rc_handle
    self.on_disconnect(self, self._userdata, rc)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 212, in on_disconnect
    logger.debug("".join(traceback.format_stack()))

07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: Forcing paho disconnect to prevent it from automatically reconnecting
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport: in paho thread.  nulling _thread
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport: Done forcing paho disconnect
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_thread: Starting _on_mqtt_disconnected in pipeline thread
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('Paho returned rc==1')
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage(DisconnectedEvent): State is LOGICALLY_CONNECTED Connected is True.
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage: State is WAITING_TO_RECONNECT. Connected=True Starting reconnect timer
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_thread: Starting _on_disconnected in callback thread
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage: disconnection was unexpected
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_thread: Starting on_reconnect_timer_expired in pipeline thread
07-30 06:07:01 [INF] azure.iot.device.common.handle_exceptions: Unexpected disconnection.  Safe to ignore since other stages will reconnect.
07-30 06:07:01 [INF] azure.iot.device.iothub.aio.async_clients: Connection State - Disconnected
07-30 06:07:01 [INF] azure.iot.device.iothub.aio.async_clients: Cleared all pending method requests due to disconnect
07-30 06:07:01 [INF] azure.iot.device.common.handle_exceptions: azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Paho returned rc==1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/handle_exceptions.py", line 43, in swallow_unraised_exception
    raise e
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('Paho returned rc==1')

07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage: Reconnect timer expired. State is WAITING_TO_RECONNECT Connected is False.
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage: sending new connect op down
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ConnectionLockStage(ConnectOperation): blocking
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage(ConnectOperation): connecting
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage(ConnectOperation): Starting watchdog
07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: connecting to mqtt broker
07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: Connect using port 8883 (TCP)
07-30 06:07:01 [DBG] paho        : Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'Delta/PythonAlgos'
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport: _mqtt_client.connect returned rc=0
07-30 06:07:01 [DBG] paho        : Received CONNACK (0, 5)
07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: connected with result code: 5
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_thread: Starting _on_mqtt_connection_failure in pipeline thread
07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: disconnected with result code: 5
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage: _on_mqtt_connection_failure called: UnauthorizedError('Connection Refused: not authorised.')
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage: failing connect op
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage(ConnectOperation): cancelling watchdog
07-30 06:07:01 [ERR] azure.iot.device.common.pipeline.pipeline_ops_base: ConnectOperation: completing with error UnauthorizedError('Connection Refused: not authorised.')
07-30 06:07:01 [ERR] azure.iot.device.common.pipeline.pipeline_stages_base: ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: UnauthorizedError('Connection Refused: not authorised.')
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport:   File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 626, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1782, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1177, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1570, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2230, in _loop_rc_handle
    self.on_disconnect(self, self._userdata, rc)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 212, in on_disconnect
    logger.debug("".join(traceback.format_stack()))

07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
07-30 06:07:01 [INF] azure.iot.device.common.mqtt_transport: Forcing paho disconnect to prevent it from automatically reconnecting
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_base: ConnectionLockStage(ConnectOperation): processing 0 items in queue
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport: in paho thread.  nulling _thread
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage(ConnectOperation): on_connect_complete error=UnauthorizedError('Connection Refused: not authorised.') state=LOGICALLY_CONNECTED never_connected=False connected=False 
07-30 06:07:01 [DBG] azure.iot.device.common.mqtt_transport: Done forcing paho disconnect
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage: completing waiting ops with error=UnauthorizedError('Connection Refused: not authorised.')
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_thread: Starting _on_mqtt_disconnected in pipeline thread
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage: _on_mqtt_disconnect called: ConnectionFailedError('The connection was refused.')
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: ReconnectStage(DisconnectedEvent): State is LOGICALLY_DISCONNECTED Connected is False.
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_stages_base: PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
07-30 06:07:01 [DBG] azure.iot.device.common.pipeline.pipeline_thread: Starting _on_disconnected in callback thread
07-30 06:07:01 [INF] azure.iot.device.common.pipeline.pipeline_stages_mqtt: MQTTTransportStage: disconnection was unexpected
07-30 06:07:01 [INF] azure.iot.device.common.handle_exceptions: Unexpected disconnection.  Safe to ignore since other stages will reconnect.
07-30 06:07:01 [INF] azure.iot.device.iothub.aio.async_clients: Connection State - Disconnected
07-30 06:07:01 [INF] azure.iot.device.iothub.aio.async_clients: Cleared all pending method requests due to disconnect
07-30 06:07:01 [INF] azure.iot.device.common.handle_exceptions: azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError('The connection was refused.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/handle_exceptions.py", line 43, in swallow_unraised_exception
    raise e
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionFailedError('The connection was refused.')
```

## Code

I'm basing my Python code off of sample code, but using the async library. This is the skeleton (haven't tested after stripping down):

```
import sys
import asyncio
from six.moves import input
import logging
from azure.iot.device.aio import IoTHubModuleClient

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)s %(name)-12s: %(message)s', datefmt='%m-%d %H:%M:%S')
logging.addLevelName(logging.WARNING, '[WRN]')
logging.addLevelName(logging.ERROR, '[ERR]')
logging.addLevelName(logging.INFO, '[INF]')
logging.addLevelName(logging.DEBUG, '[DBG]')
applogger = logging.getLogger('app')

async def main():

    try:
        if not sys.version >= "3.5.3":
            raise Exception( "Requires python 3.5.3+. Current version of Python: %s" % sys.version )
        applogger.debug( "IoT Hub Client for Python" )

        # The module client object is used to interact with your Azure IoT hub.
        module_client = IoTHubModuleClient.create_from_edge_environment()

        # connect the module client.
        await module_client.connect()

        async def cmd_listener(module_client):
            while True:
                cmd_msg = await module_client.receive_message_on_input("cmdin")

                try:
                    msg_str = cmd_msg.data.decode("utf-8").lower()
                    applogger.debug(msg_str)

                except Exception as ex:
                    applogger.error("Unexpected error in cmd_listener: %s" % ex)

        async def input_listener(module_client):
            while True:
                msg = await module_client.receive_message_on_input("input")

                try:
                    msg_str = msg.data.decode("utf-8").lower()
                    applogger.debug(msg_str)
                    
                except Exception as ex:
                    applogger.error("Unexpected error in input_listener: %s" % ex)
        
        async def twin_patch_listener(module_client):
            while True:
                try:
                    data = await module_client.receive_twin_desired_properties_patch()
                    applogger.debug( "The data in the desired properties patch was: %s" % data)

                    reported_patch = {"report": "test"}    
                    await module_client.patch_twin_reported_properties(reported_patch)

                except Exception as ex:
                    applogger.error ( "Unexpected error in twin_patch_listener: %s" % ex )

        def stdin_listener():
            while True:
                time.sleep(10)


        loop = asyncio.get_event_loop()
        listeners = asyncio.gather(cmd_listener(module_client), input_listener(module_client), twin_patch_listener(module_client))

        # Run the stdin listener in the event loop
        user_finished = loop.run_in_executor(None, stdin_listener)

        # Wait for user to indicate they are done listening for messages
        await user_finished

        # Cancel listening
        listeners.cancel()

        # Finally, disconnect
        await module_client.disconnect()

    except Exception as e:
        applogger.error ( "Unexpected error %s " % e )
        raise


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.set_debug(True)
    loop.run_until_complete(main())
    loop.close()
```

AB#7846882

**Comment by olivakar** [comment]
can you please provide your entire log of Module B by enabling logging set to DEBUG ?
it will be easier if you can save the log in a file as well.

Also please also enable logging for this specific library
logging.getLogger("paho").setLevel(level=logging.DEBUG)

From the logs it shows that for the module ABS connections are removed (`connection removed for device Delta/azureblobstorageoniotedge`) but I am guessing ABS is able to then re-authenticate and renew their connection and then Module A continues sending data to the cloud through ABS. But module B (the python one) is not able to. The logs for ABS does not show successful re-connection , so I am just verifying that it is the case.

**Comment by elhorton** [comment]
hi @ryayl , due to lack of  response, we're going to close this issue. please reopen if this is still a problem. thanks!

**Comment by az-iot-builder-01** [comment]
@ryayl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
