### ISSUE TITLE
provision_x509.py running issue

### ISSUE THREAD

**Issue by PradeepKiruvale** [Azure/azure-iot-sdk-python#730]
Hi All,

I am using provision_x509.py to autoprovisioning of my devices using DPS. Have couple of issues
Did not understand what exactly is  pass_phrase is?
Does provisiong host means? "https://global.azure-devices-provisioning.net"?

Getting below error when I run, offcourse I added my own certs,dps 

Any help here?

Thanks,
Pradeep

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 394, in connect
    rc = self._mqtt_client.connect(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/provisioning/aio/async_provisioning_device_client.py", line 29, in handle_result
    return await callback.completion()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
    return await self.future
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 193, in _run_op
    self.transport.connect(password=password)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 417, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by gaierror(-2, 'Name or service not known')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "provision_x509.py", line 68, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "provision_x509.py", line 35, in main
    registration_result = await provisioning_device_client.register()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/provisioning/aio/async_provisioning_device_client.py", line 76, in register
    await self._enable_responses()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/provisioning/aio/async_provisioning_device_client.py", line 103, in _enable_responses
    await handle_result(subscription_complete)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/iot/device/provisioning/aio/async_provisioning_device_client.py", line 33, in handle_result
    raise exceptions.ConnectionFailedError(message="Could not connect to IoTHub", cause=e)
azure.iot.device.exceptions.ConnectionFailedError: ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)

**Comment by olivakar** [comment]
Could you se if the following link answers your questions/concerns ?

https://github.com/Azure/azure-iot-sdk-python/wiki/X509_Chain

**Comment by olivakar** [comment]
Did not understand what exactly is pass_phrase is?  
  - is the password with which you create certificate

Does provisiong host means? "https://global.azure-devices-provisioning.net"? 
- Just `global.azure-devices-provisioning.net`

**Comment by PradeepKiruvale** [comment]
I could make it to work. Some things are not very clear from the code/document. So, I had to do some trail n error.
Since it works now, I am happy to close this issue now.

**Comment by olivakar** [comment]
The WIKI document is written for a different purpose as many of the things about hostname/registration_id along with certification creation are confusing. 

But could you elaborate how would you want the code in the sample to be updated ?

Is this related to the passphrase and the hostname thing ?
