### ISSUE TITLE
'IoTHubRegistryManager' object has no attribute 'amqp_svc_client'

### ISSUE THREAD

**Issue by moizhraj** [Azure/azure-iot-sdk-python#740]
- **OS and version used:** Windows 10 20H2, Build 19042.746
- **Python version:** 3.8.7 64 bit
- **pip version:** 20.2.3
- **list of installed packages:**
    Package - Version
    ------------------------------ ---------
    astroid                        2.4.2    
    azure-cognitiveservices-speech 1.15.0   
    azure-iot-device               2.5.1    
    azure-iot-hub                  2.2.3    
    certifi                        2020.12.5
    chardet                        4.0.0    
    colorama                       0.4.4    
    deprecation                    2.1.0    
    idna                           2.10     
    isodate                        0.6.0    
    isort                          5.7.0    
    janus                          0.4.0    
    lazy-object-proxy              1.4.3    
    mccabe                         0.6.1    
    msrest                         0.6.21   
    oauthlib                       3.1.0    
    packaging                      20.9     
    paho-mqtt                      1.5.1    
    pip                            20.2.3   
    pylint                         2.6.0    
    pyparsing                      2.4.7
    PySocks                        1.7.1
    requests                       2.25.1
    requests-oauthlib              1.3.0
    requests-unixsocket            0.2.0
    setuptools                     49.2.1
    six                            1.15.0
    toml                           0.10.2
    uamqp                          1.2.15
    urllib3                        1.25.11
    wrapt                          1.12.1

Following [this ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-c2d) documentation. Even without any of my integration, it is throwing an error "'IoTHubRegistryManager' object has no attribute 'amqp_svc_client'" when sending a message to device.

here are the logs

```
Traceback (most recent call last):
  File "main.py", line 38, in iothub_c2d_message
    registry_manager = IoTHubRegistryManager(C2D_CONNECTION_STRING)
  File "\.venv\lib\site-packages\azure\iot\hub\iothub_registry_manager.py", line 68, in __init__
    self.auth["HostName"], self.auth["SharedAccessKeyName"], self.auth["SharedAccessKey"]
  File "\.venv\lib\site-packages\azure\iot\hub\connection_string.py", line 78, in __getitem__
    return self._dict[key]
KeyError: 'SharedAccessKeyName'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 165, in <module>
    speech_recognize_keyword_locally_from_microphone()
  File "main.py", line 153, in speech_recognize_keyword_locally_from_microphone
    capture_speech()
  File "main.py", line 96, in capture_speech
    iothub_c2d_message(intent_to_command_map[intent_result.intent_id])
  File "main.py", line 51, in iothub_c2d_message
    print ( "Unexpected error {0}" % ex )
TypeError: not all arguments converted during string formatting
Exception ignored in: <function IoTHubRegistryManager.__del__ at 0x000001696A211820>
Traceback (most recent call last):
  File "\.venv\lib\site-packages\azure\iot\hub\iothub_registry_manager.py", line 75, in __del__
    self.amqp_svc_client.disconnect_sync()
AttributeError: 'IoTHubRegistryManager' object has no attribute 'amqp_svc_client'
```

**Comment by cartertinney** [comment]
@moizhraj Are you sure you are using the correct connection string for the service client? It appears the connection string you have provided does not have a SharedAccessKeyName, which should be present.

**Comment by cartertinney** [comment]
Closing due to inactivity. If you cannot resolve your issue please reopen an issue on this topic.

**Comment by zh0903** [comment]
I encounter the same error with 2.0.2, but solve it by:
$pip install azure-iot-hub -U 
Update IoT-HUB dependency to 
azure-iot-hub       2.6.1
make example code work.
