### ISSUE TITLE
Trying to send message to IoT Hub using azure sdk but getting 'certfile should be a valid filesystem path' error

### ISSUE THREAD

**Issue by RohitMundhra** [Azure/azure-iot-sdk-python#835]
I am using one of the sample code provided by this git repo **azure-iot-sdk-python/azure-iot-device/samples/async-hub-scenarios/send_message_x509.py** and trying to connect my Iot Device to IoT Hub but getting an error. I am sending my code and error. Please help

**Code**

# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# --------------------------------------------------------------------------

import os
import uuid
from azure.iot.device.aio import IoTHubDeviceClient
from azure.iot.device import Message, X509
import asyncio

messages_to_send = 10

async def main():
    hostname = os.getenv("WE-SB-DEV-SC-iothub02.azure-devices.net")
    # The device that has been created on the portal using X509 CA signing or Self signing capabilities
    device_id = os.getenv("leafrootca")

    x509 = X509(
        cert_file=os.getenv("/Users/r0m086g/Documents/DeviceCerti/iot-device-leafrootca-primary.cert.pem"),
        key_file=os.getenv("/Users/r0m086g/Documents/DeviceCerti/iot-device-leafrootca-primary.key.pem"),
        pass_phrase=os.getenv("1234")
    )

    # The client object is used to interact with your Azure IoT hub.
    device_client = IoTHubDeviceClient.create_from_x509_certificate(
        hostname=hostname, device_id=device_id, x509=x509
    )

    # Connect the client.
    await device_client.connect()

    async def send_test_message(i):
        print("sending message #" + str(i))
        msg = Message("test wind speed " + str(i))
        msg.message_id = uuid.uuid4()
        msg.correlation_id = "correlation-1234"
        msg.custom_properties["tornado-warning"] = "yes"
        msg.content_encoding = "utf-8"
        msg.content_type = "application/json"
        await device_client.send_message(msg)
        print("done sending message #" + str(i))

    # send `messages_to_send` messages in parallel
    await asyncio.gather(*[send_test_message(i) for i in range(1, messages_to_send + 1)])

    # Finally, shut down the client
    await device_client.shutdown()

if __name__ == "__main__":
    asyncio.run(main())

    # If using Python 3.6 or below, use the following code instead of asyncio.run(main()):
    # loop = asyncio.get_event_loop()
    # loop.run_until_complete(main())
    # loop.close()

**Error**

Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_http.HTTPTransportStage object at 0x7fd77de159a0>._run_op() call
Traceback (most recent call last):
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 103, in run_op
    self._run_op(op)
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 203, in wrapper
    return func(*args, **kwargs)
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/pipeline/pipeline_stages_http.py", line 62, in _run_op
    self.transport = HTTPTransport(
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/http_transport.py", line 37, in __init__
    self._ssl_context = self._create_ssl_context()
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/http_transport.py", line 60, in _create_ssl_context
    ssl_context.load_cert_chain(
**TypeError: certfile should be a valid filesystem path**

Traceback (most recent call last):
  File "/Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py", line 55, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py", line 29, in main
    device_client = IoTHubDeviceClient.create_from_x509_certificate(
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/aio/patch_documentation.py", line 114, in create_from_x509_certificate
    return super(IoTHubDeviceClient_, cls).create_from_x509_certificate(
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/iothub/abstract_clients.py", line 498, in create_from_x509_certificate
    http_pipeline = pipeline.HTTPPipeline(pipeline_configuration)
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/iothub/pipeline/http_pipeline.py", line 65, in __init__
    callback.wait_for_completion()
(base) r0m086g@m-c02d14uwmd6n Leafdevice % /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_http.HTTPTransportStage object at 0x7fea2e1e39a0>._run_op() call
Traceback (most recent call last):
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 103, in run_op
    self._run_op(op)
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 203, in wrapper
    return func(*args, **kwargs)
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/pipeline/pipeline_stages_http.py", line 62, in _run_op
    self.transport = HTTPTransport(
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/http_transport.py", line 37, in __init__
    self._ssl_context = self._create_ssl_context()
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/common/http_transport.py", line 60, in _create_ssl_context
    ssl_context.load_cert_chain(
**TypeError: certfile should be a valid filesystem path**

**Comment by cartertinney** [comment]
@RohitMundhra 

`os.getenv()` is a python built-in function that fetches a environment variable. You seem to be trying to provide a filesystem path to it instead of the name of a variable where the path is stored.

Try just passing the filepath strings directly as the arguments `cert_file` and `key_file` without use of the `os.getenv()` function

**Comment by RohitMundhra** [comment]
Thanks. It worked. 
The function by default uses mqtt to connect with IoT Hub but in my system Mqtt is blocked so I wanted to send msg via Amqp port. Can you help me regarding the same as to how to specify to send msg through Amqp port

**Comment by RohitMundhra** [comment]
Instead of Amqp i use websocket port and it worked. Is it possible to use the sdk to connect my leaf device to Iot Hub via edge Gateway? I have already created child- parent relation.

**Comment by cartertinney** [comment]
The Azure IoT Device SDK for Python does not support AMQP, but I am glad that websockets are working for you.

As for using Edge, the SDK does support Edge environments, with the `.create_from_edge_environment()` factory method, if your environment variables have been set up for Edge.

**Comment by RohitMundhra** [comment]
Now I was trying to connect my IoT Device to IoT Hub via IoT Edge Device. So it will send data to iot Edge Hub which will forward it to IoT Hub.

**Here is the Code:**

# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# --------------------------------------------------------------------------
import os
import uuid
from azure.iot.device.aio import IoTHubDeviceClient
from azure.iot.device import Message, X509
import asyncio


messages_to_send = 10


async def main():
    hostname = "weiotedge.s05296.us.wal-mart.com"
    device_id ="leafrootca"
    root_ca="/Users/r0m086g/Documents/DeviceCerti/azure-iot-test-only.root.ca.cert.pem"
    certfile = open(root_ca)
    root_ca_cert = certfile.read()

    x509 = X509(
        cert_file="/Users/r0m086g/Documents/DeviceCerti/iot-device-leafrootca-primary.cert.pem",
        key_file="/Users/r0m086g/Documents/DeviceCerti/iot-device-leafrootca-primary.key.pem",
        pass_phrase="1234"
    )
    
    
    device_client = IoTHubDeviceClient.create_from_x509_certificate(
        hostname=hostname, device_id=device_id, x509=x509, server_verification_cer=root_ca_cert, websockets=True, 
    )
    
    # Connect the client.
    await device_client.connect()

    async def send_test_message(i):
        print("sending message #" + str(i))
        msg = Message("test wind speed " + str(i))
        msg.message_id = uuid.uuid4()
        msg.correlation_id = "correlation-1234"
        msg.custom_properties["tornado-warning"] = "yes"
        msg.content_encoding = "utf-8"
        msg.content_type = "application/json"
        await device_client.send_message(msg)
        print("done sending message #" + str(i))

    # send `messages_to_send` messages in parallel
    await asyncio.gather(*[send_test_message(i) for i in range(1, messages_to_send + 1)])

    # Finally, shut down the client
    await device_client.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
 

**Error:**
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py
(base) r0m086g@m-c02d14uwmd6n Leafdevice % /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py
Traceback (most recent call last):
  File "/Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py", line 68, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/r0m086g/Desktop/IOT_Platform_Tasks/Leafdevice/leafAmqp.py", line 42, in main
    device_client = IoTHubDeviceClient.create_from_x509_certificate(
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/aio/patch_documentation.py", line 114, in create_from_x509_certificate
    return super(IoTHubDeviceClient_, cls).create_from_x509_certificate(
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/iothub/abstract_clients.py", line 488, in create_from_x509_certificate
    _validate_kwargs(exclude=excluded_kwargs, **kwargs)
  File "/Users/r0m086g/Library/Python/3.8/lib/python/site-packages/azure/iot/device/iothub/abstract_clients.py", line 45, in _validate_kwargs
    raise TypeError("Unsupported keyword argument: '{}'".format(kwarg))
TypeError: Unsupported keyword argument: 'server_verification_cer'

Can you please help why it is saying thet server_verification_cer is not supported.  According to https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.iothubdeviceclient?view=azure-python#create-from-x509-certificate-x509--hostname--device-id----kwargs- it is valid

**Comment by cartertinney** [comment]
@RohitMundhra You have a typo. You used the keyword ` server_verification_cer` instead of ` server_verification_cert`

**Comment by RohitMundhra** [comment]
Thanks @cartertinney 
I am now trying to connect to my iot Hub via my edge hub of my edge gateway device. I am able to connect with edge hub but not able to send data to IoT hub. Getting error: "

**Code**
import os
import uuid
from azure.iot.device.aio import IoTHubDeviceClient
from azure.iot.device import Message, X509
import asyncio


messages_to_send = 10


async def main():
    #hostname = "WE-SB-DEV-SC-iothub02.azure-devices.net"
    hostname = "weiotedge.s05296.us.wal-mart.com"
    # The device that has been created on the portal using X509 CA signing or Self signing capabilities
    #device_id = os.getenv("leafrootca")
    device_id ="leafrootca"
    #device_id ="leafdevice"
    #root_ca="/Users/r0m086g/Documents/DeviceCerti/azure-iot-test-only.root.ca.cert.pem"
    #root_ca="/Users/r0m086g/Documents/DeviceCerti/azure-iot-test-only.intermediate-full-chain.cert.pem"
    #root_ca="/home/weiotadm/iotedge/tools/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem"
    #root_ca="/Users/r0m086g/Documents/DeviceCerti/iot-edge-device-ca-deviceCAcertificate.cert.pem"
    #certfile = open(root_ca)
    #root_ca_cert = certfile.read()

    x509 = X509(
        #cert_file=os.getenv("PUB_KEY),
        #key_file=os.getenv(PRVT_KEY),
        #pass_phrase=os.getenv(PASS)
        
        cert_file="/home/weiotadm/iotedge/tools/CACertificates/certs/iot-device-leafrootca-primary.cert.pem",
        key_file="/home/weiotadm/iotedge/tools/CACertificates/private/iot-device-leafrootca-primary.key.pem",
        #cert_file="/Users/r0m086g/Documents/DeviceCerti/cert.pem",
        #key_file="/Users/r0m086g/Documents/DeviceCerti/key.pem",
        #cert_file="/home/weiotadm/device/cert.pem",
        #key_file="/home/weiotadm/device/key.pem",
        pass_phrase="1234"
    )
    #server_verification_cer=root_ca_cer
    # The client object is used to interact with your Azure IoT hub.
    device_client = IoTHubDeviceClient.create_from_x509_certificate(
        x509=x509, hostname=hostname, device_id=device_id, websockets=True, 
    )
    
    # Connect the client.
    await device_client.connect()

    async def send_test_message(i):
        print("sending message #" + str(i))
        msg = Message("test wind speed " + str(i))
        msg.message_id = uuid.uuid4()
        msg.correlation_id = "correlation-1234"
        msg.custom_properties["tornado-warning"] = "yes"
        msg.content_encoding = "utf-8"
        msg.content_type = "application/json"
        await device_client.send_message(msg)
        print("done sending message #" + str(i))

    # send `messages_to_send` messages in parallel
    await asyncio.gather(*[send_test_message(i) for i in range(1, messages_to_send + 1)])

    # Finally, shut down the client
    await device_client.shutdown()


if __name__ == "__main__":
    #asyncio.run(main())
    # If using Python 3.6 or below, use the following code instead of asyncio.run(main()):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()

**Error**
6> 2021-08-16 08:42:30.811 +00:00 [INF] - Setting device proxy inactive for device Id leafrootca
<6> 2021-08-16 08:42:30.811 +00:00 [INF] - Removing device connection for device leafrootca with removeCloudConnection flag 'True'.
<6> 2021-08-16 08:42:30.812 +00:00 [INF] - Closing receiver in cloud proxy e76e2f33-7ad0-44b7-96ef-35428541b7f2 for leafrootca
<6> 2021-08-16 08:42:30.813 +00:00 [INF] - Closed cloud proxy e76e2f33-7ad0-44b7-96ef-35428541b7f2 for leafrootca
<6> 2021-08-16 08:42:30.813 +00:00 [INF] - Device connection removed for device leafrootca
<6> 2021-08-16 08:42:30.814 +00:00 [INF] - Remove device connection for device leafrootca
<6> 2021-08-16 08:42:30.814 +00:00 [INF] - Transport closed. CorrelationId 7c1c7fc0
<6> 2021-08-16 08:42:31.140 +00:00 [INF] - Updated reported properties for certificatetest/$edgeHub
<6> 2021-08-16 08:43:28.825 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-08-16 08:47:47.850 +00:00 [INF] - Request starting HTTP/1.1 GET https://weiotedge.s05296.us.wal-mart.com:443/$iothub/websocket  
<6> 2021-08-16 08:47:47.853 +00:00 [INF] - Processed MQTT WebSocket request with CorrelationId b309a9d6-76c8-49c8-9824-2534b47fa744
<6> 2021-08-16 08:47:47.960 +00:00 [INF] - Client leafrootca in device scope authenticated locally.
<6> 2021-08-16 08:47:47.962 +00:00 [INF] - Successfully generated identity for clientId leafrootca and username weiotedge.s05296.us.wal-mart.com/leafrootca/?api-version=2019-10-01&DeviceClientType=azure-iot-device-iothub-py%2F2.7.1%283.6.8%3BLinux%20%231%20SMP%20Tue%20Feb%204%2023%3A02%3A59%20UTC%202020%3Bx86_64%29
<6> 2021-08-16 08:47:47.962 +00:00 [INF] - ClientAuthenticated, leafrootca, 3efb54ec
<6> 2021-08-16 08:47:47.963 +00:00 [INF] - New device connection for device leafrootca
<6> 2021-08-16 08:47:47.964 +00:00 [INF] - Client leafrootca connected to edgeHub, processing existing subscriptions.
<6> 2021-08-16 08:47:47.967 +00:00 [INF] - Bind device proxy for device leafrootca
<6> 2021-08-16 08:47:47.967 +00:00 [INF] - Binding message channel for device Id leafrootca
<6> 2021-08-16 08:47:47.967 +00:00 [INF] - Attempting to connect to IoT Hub for client leafrootca via AMQP...
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Cloud connection for leafrootca is True
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Connection status for leafrootca changed to ConnectionEstablished
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Client leafrootca connected to cloud, processing existing subscriptions.
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Skipping leafrootca for subscription processing, as it is currently being processed.
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Created cloud proxy for client leafrootca via AMQP, with client operation timeout 20 seconds.
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Initialized cloud proxy e1b09c4e-a839-409e-894c-2284682e2d84 for leafrootca
<6> 2021-08-16 08:47:48.181 +00:00 [INF] - Created cloud connection for client leafrootca
<6> 2021-08-16 08:47:48.270 +00:00 [INF] - Updated reported properties for certificatetest/$edgeHub
<6> 2021-08-16 08:48:28.826 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-08-16 08:48:59.187 +00:00 [INF] - Closing connection for device: leafrootca, , 
<6> 2021-08-16 08:48:59.187 +00:00 [INF] - Disposing MessagingServiceClient for device Id leafrootca because of exception - 
<6> 2021-08-16 08:48:59.188 +00:00 [INF] - Setting device proxy inactive for device Id leafrootca
<6> 2021-08-16 08:48:59.188 +00:00 [INF] - Removing device connection for device leafrootca with removeCloudConnection flag 'True'.
<6> 2021-08-16 08:48:59.190 +00:00 [INF] - Closing receiver in cloud proxy e1b09c4e-a839-409e-894c-2284682e2d84 for leafrootca
<6> 2021-08-16 08:48:59.190 +00:00 [INF] - Closed cloud proxy e1b09c4e-a839-409e-894c-2284682e2d84 for leafrootca
<6> 2021-08-16 08:48:59.190 +00:00 [INF] - Device connection removed for device leafrootca
<6> 2021-08-16 08:48:59.191 +00:00 [INF] - Remove device connection for device leafrootca
<6> 2021-08-16 08:48:59.191 +00:00 [INF] - Transport closed. CorrelationId 3efb54ec
<4> 2021-08-16 08:48:59.193 +00:00 [WRN] - Error closing transport. CorrelationId 3efb54ec
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoClose() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 99
<6> 2021-08-16 08:48:59.196 +00:00 [INF] - Transport aborted. CorrelationId 3efb54ec
<6> 2021-08-16 08:48:59.197 +00:00 [INF] - Request finished in 71347.5045ms 101 
<6> 2021-08-16 08:48:59.504 +00:00 [INF] - Updated reported properties for certificatetest/$edgeHub

Can you please help. Trying to solve this issue for past 4 days

**Comment by cartertinney** [comment]
Can you add the following lines to the beginning of your code, and post the output so I can see some more detailed logs?

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by cartertinney** [comment]
Closing due to inactivity.
