### ISSUE TITLE
Unusual/poor connection to IoT Hub

### ISSUE THREAD

**Issue by kodonnell** [Azure/azure-iot-sdk-python#837]
I'm not sure if this is related to #812 or #810 but it seems to me that the client gets stuck in a state where it can't send any messages. I'm not completely certain as at this stage it could still be other things - and it's also odd as some devices seen fine, and others not.

I'm basically following [this](https://github.com/Azure/azure-iot-sdk-python/blob/c6a7be37ec6af2136faef11cc4bc4e33c88434ce/azure-iot-device/samples/sync-samples/send_message.py) example, and

- On Raspberry Pi 3A+ with Raspbian
- Over a low bandwidth (15kb) cellular connection
- Python 3.7
-  and
```sh
$ pip freeze | grep azure
azure-core==1.16.0
azure-iot-device==2.7.1
azure-iot-hub==2.4.0
```

Firstly

```
Aug 12 07:56:29 *** python[508]: ReconnectStage: DisconnectEvent received while in unexpected state - WAITING_TO_RECONNECT, Connected: False
```

Which seems odd because of [here](https://github.com/Azure/azure-iot-sdk-python/blob/c6a7be37ec6af2136faef11cc4bc4e33c88434ce/azure-iot-device/azure/iot/device/common/pipeline/pipeline_stages_base.py#L1120-L1126), and the comment `# BAD STATE (this block should not be reached)` but I obviously have reached it. When I run without changing the loglevel, I just see those repeating and no other warnings etc. When I enabled debug logging, I'm seeing the below - unfortunately it doesn't include the above message (as getting logs is difficult) but it may point to an error. I will try to get more complete logs if possible.

```
-- Logs begin at Thu 2021-08-12 07:39:45 NZST, end at Thu 2021-08-12 08:05:14 NZST. --
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting on_reconnect_timer_expired in pipeline thread
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: Reconnect timer expired. State is WAITING_TO_RECONNECT Connected is False.
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: sending new connect op down
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): blocking
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): connecting
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): Starting watchdog
Aug 12 08:02:57 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:connecting to mqtt broker
Aug 12 08:02:57 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Connect using port 8883 (TCP)
Aug 12 08:03:02 *** python[17028]: DEBUG:paho:Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'***'
Aug 12 08:03:02 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:_mqtt_client.connect returned rc=0
Aug 12 08:03:03 *** python[17028]: DEBUG:paho:Received CONNACK (1, 0)
Aug 12 08:03:03 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:connected with result code: 0
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_connected in pipeline thread
Aug 12 08:03:03 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:_on_mqtt_connected called
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: ConnectedEvent received. Calling on_connected_handler
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_connected in callback thread
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:completing connect op
Aug 12 08:03:03 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Connection State - Connected
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): cancelling watchdog
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:ConnectOperation: completing without error
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): op succeeded.  Unblocking queue
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): processing 0 items in queue for error=None
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(ConnectOperation): on_connect_complete error=None state=LOGICALLY_CONNECTED never_connected=False connected=True
Aug 12 08:03:03 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: completing waiting ops with error=None
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:disconnected with result code: 1
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
Aug 12 08:03:04 *** python[17028]:     self._bootstrap_inner()
Aug 12 08:03:04 *** python[17028]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Aug 12 08:03:04 *** python[17028]:     self.run()
Aug 12 08:03:04 *** python[17028]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Aug 12 08:03:04 *** python[17028]:     self._target(*self._args, **self._kwargs)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
Aug 12 08:03:04 *** python[17028]:     self.loop_forever(retry_first_connection=True)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
Aug 12 08:03:04 *** python[17028]:     rc = self.loop(timeout, max_packets)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1181, in loop
Aug 12 08:03:04 *** python[17028]:     rc = self.loop_read(max_packets)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1574, in loop_read
Aug 12 08:03:04 *** python[17028]:     return self._loop_rc_handle(rc)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 2227, in _loop_rc_handle
Aug 12 08:03:04 *** python[17028]:     self._do_on_disconnect(rc, properties)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
Aug 12 08:03:04 *** python[17028]:     self.on_disconnect(self, self._userdata, rc)
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 210, in on_disconnect
Aug 12 08:03:04 *** python[17028]:     logger.debug("".join(traceback.format_stack()))
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Forcing paho disconnect to prevent it from automatically reconnecting
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:in paho thread.  nulling _thread
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:Done forcing paho disconnect
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_disconnected in pipeline thread
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(DisconnectedEvent): State is LOGICALLY_CONNECTED Connected is True.
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(DisconnectedEvent): Attempting to reconnect
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_disconnected in callback thread
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: disconnection was unexpected
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Connection State - Disconnected
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Cleared all pending method requests due to disconnect
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.handle_exceptions:Unexpected disconnection
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.handle_exceptions:azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:04 *** python[17028]: The above exception was the direct cause of the following exception:
Aug 12 08:03:04 *** python[17028]: Traceback (most recent call last):
Aug 12 08:03:04 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/handle_exceptions.py", line 43, in swallow_unraised_exception
Aug 12 08:03:04 *** python[17028]:     raise e
Aug 12 08:03:04 *** python[17028]: azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting on_reconnect_timer_expired in pipeline thread
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: Reconnect timer expired. State is WAITING_TO_RECONNECT Connected is False.
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: sending new connect op down
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): blocking
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): connecting
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): Starting watchdog
Aug 12 08:03:04 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:connecting to mqtt broker
Aug 12 08:03:04 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Connect using port 8883 (TCP)
Aug 12 08:03:10 *** python[17028]: DEBUG:paho:Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'***'
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:_mqtt_client.connect returned rc=0
Aug 12 08:03:10 *** python[17028]: DEBUG:paho:Received CONNACK (1, 0)
Aug 12 08:03:10 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:connected with result code: 0
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_connected in pipeline thread
Aug 12 08:03:10 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:_on_mqtt_connected called
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: ConnectedEvent received. Calling on_connected_handler
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_connected in callback thread
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:completing connect op
Aug 12 08:03:10 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Connection State - Connected
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): cancelling watchdog
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:ConnectOperation: completing without error
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): op succeeded.  Unblocking queue
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): processing 0 items in queue for error=None
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(ConnectOperation): on_connect_complete error=None state=LOGICALLY_CONNECTED never_connected=False connected=True
Aug 12 08:03:10 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: completing waiting ops with error=None
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:disconnected with result code: 1
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
Aug 12 08:03:14 *** python[17028]:     self._bootstrap_inner()
Aug 12 08:03:14 *** python[17028]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Aug 12 08:03:14 *** python[17028]:     self.run()
Aug 12 08:03:14 *** python[17028]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Aug 12 08:03:14 *** python[17028]:     self._target(*self._args, **self._kwargs)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
Aug 12 08:03:14 *** python[17028]:     self.loop_forever(retry_first_connection=True)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
Aug 12 08:03:14 *** python[17028]:     rc = self.loop(timeout, max_packets)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1181, in loop
Aug 12 08:03:14 *** python[17028]:     rc = self.loop_read(max_packets)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1574, in loop_read
Aug 12 08:03:14 *** python[17028]:     return self._loop_rc_handle(rc)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 2227, in _loop_rc_handle
Aug 12 08:03:14 *** python[17028]:     self._do_on_disconnect(rc, properties)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
Aug 12 08:03:14 *** python[17028]:     self.on_disconnect(self, self._userdata, rc)
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 210, in on_disconnect
Aug 12 08:03:14 *** python[17028]:     logger.debug("".join(traceback.format_stack()))
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Forcing paho disconnect to prevent it from automatically reconnecting
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:in paho thread.  nulling _thread
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:Done forcing paho disconnect
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_disconnected in pipeline thread
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(DisconnectedEvent): State is LOGICALLY_CONNECTED Connected is True.
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(DisconnectedEvent): Attempting to reconnect
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_disconnected in callback thread
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: disconnection was unexpected
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Connection State - Disconnected
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Cleared all pending method requests due to disconnect
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.handle_exceptions:Unexpected disconnection
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.handle_exceptions:azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:14 *** python[17028]: The above exception was the direct cause of the following exception:
Aug 12 08:03:14 *** python[17028]: Traceback (most recent call last):
Aug 12 08:03:14 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/handle_exceptions.py", line 43, in swallow_unraised_exception
Aug 12 08:03:14 *** python[17028]:     raise e
Aug 12 08:03:14 *** python[17028]: azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting on_reconnect_timer_expired in pipeline thread
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: Reconnect timer expired. State is WAITING_TO_RECONNECT Connected is False.
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: sending new connect op down
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): blocking
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): connecting
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): Starting watchdog
Aug 12 08:03:14 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:connecting to mqtt broker
Aug 12 08:03:14 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Connect using port 8883 (TCP)
Aug 12 08:03:20 *** python[17028]: DEBUG:paho:Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'***'
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:_mqtt_client.connect returned rc=0
Aug 12 08:03:20 *** python[17028]: DEBUG:paho:Received CONNACK (1, 0)
Aug 12 08:03:20 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:connected with result code: 0
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_connected in pipeline thread
Aug 12 08:03:20 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:_on_mqtt_connected called
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: ConnectedEvent received. Calling on_connected_handler
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_connected in callback thread
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:completing connect op
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): cancelling watchdog
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:ConnectOperation: completing without error
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): op succeeded.  Unblocking queue
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): processing 0 items in queue for error=None
Aug 12 08:03:20 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Connection State - Connected
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(ConnectOperation): on_connect_complete error=None state=LOGICALLY_CONNECTED never_connected=False connected=True
Aug 12 08:03:20 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: completing waiting ops with error=None
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:disconnected with result code: 1
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
Aug 12 08:03:22 *** python[17028]:     self._bootstrap_inner()
Aug 12 08:03:22 *** python[17028]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Aug 12 08:03:22 *** python[17028]:     self.run()
Aug 12 08:03:22 *** python[17028]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Aug 12 08:03:22 *** python[17028]:     self._target(*self._args, **self._kwargs)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3452, in _thread_main
Aug 12 08:03:22 *** python[17028]:     self.loop_forever(retry_first_connection=True)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
Aug 12 08:03:22 *** python[17028]:     rc = self.loop(timeout, max_packets)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1181, in loop
Aug 12 08:03:22 *** python[17028]:     rc = self.loop_read(max_packets)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1574, in loop_read
Aug 12 08:03:22 *** python[17028]:     return self._loop_rc_handle(rc)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 2227, in _loop_rc_handle
Aug 12 08:03:22 *** python[17028]:     self._do_on_disconnect(rc, properties)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
Aug 12 08:03:22 *** python[17028]:     self.on_disconnect(self, self._userdata, rc)
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 210, in on_disconnect
Aug 12 08:03:22 *** python[17028]:     logger.debug("".join(traceback.format_stack()))
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Forcing paho disconnect to prevent it from automatically reconnecting
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:in paho thread.  nulling _thread
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:Done forcing paho disconnect
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_disconnected in pipeline thread
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(DisconnectedEvent): State is LOGICALLY_CONNECTED Connected is True.
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage(DisconnectedEvent): Attempting to reconnect
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_disconnected in callback thread
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: disconnection was unexpected
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.handle_exceptions:Unexpected disconnection
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.handle_exceptions:azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:22 *** python[17028]: The above exception was the direct cause of the following exception:
Aug 12 08:03:22 *** python[17028]: Traceback (most recent call last):
Aug 12 08:03:22 *** python[17028]:   File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/handle_exceptions.py", line 43, in swallow_unraised_exception
Aug 12 08:03:22 *** python[17028]:     raise e
Aug 12 08:03:22 *** python[17028]: azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('Paho returned rc==1')
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Connection State - Disconnected
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.iothub.abstract_clients:Cleared all pending method requests due to disconnect
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting on_reconnect_timer_expired in pipeline thread
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: Reconnect timer expired. State is WAITING_TO_RECONNECT Connected is False.
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ReconnectStage: sending new connect op down
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionLockStage(ConnectOperation): blocking
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): connecting
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): Starting watchdog
Aug 12 08:03:22 *** python[17028]: DEBUG:azure.iot.device.common.mqtt_transport:connecting to mqtt broker
Aug 12 08:03:22 *** python[17028]: INFO:azure.iot.device.common.mqtt_transport:Connect using port 8883 (TCP)
```

Any thoughts, or things I can do to help debug?

**Comment by cartertinney** [comment]
@kodonnell 

I'm currently working on some various fixes for this portion of the code. I have also run into this issue before in the past, although can't quite reliably produce it, I suspect it has to do with a race condition wrt to logical connection state vs. actual connection state.

The changes I'm working on should hopefully fix this issue, and I expect it to be released in about a week and half or so. Hopefully it won't be too much of an issue until then

**Comment by kodonnell** [comment]
Oh right. I think I saw some other threads around GIL etc. - and while none of my code should be having those problems, the pi is getting a little thrashed so race conditions might not be out of the question.

In the interim, are there any quick workarounds e.g. recreating the device client every time I send a message, or sending messages in a different way (e.g. not synchronous)?

**Comment by cartertinney** [comment]
I would certainly not advise creating many clients rapidly, that will likely lead to additional problems. 

You could try disabling the automatic retry of connections with the `connection_retry=False` parameter to avoid the issue, but this will come with it's own drawbacks:
1) The client won't automatically retry the connection if it drops, so you will be responsible for re-establishing it. You may be able to use the `.on_disconnected` handler to trigger some process to do this.
2) If you are using connection string or edge environment auth while connection retry is disabled, there is a known bug where SAS tokens will not automatically renew, and so you'd have to probably tear down and re-create the client every ~58 minutes (or 2 minutes shy of whatever your configured token lifespan is)

**Comment by kodonnell** [comment]
Sorry to be a pest @cartertinney but any update on this one?

**Comment by cartertinney** [comment]
PR #844 will hopefully address these issues

**Comment by cartertinney** [comment]
PR #844 has been merged. We are doing some final testing before release.

**Comment by cartertinney** [comment]
@kodonnell

We released a package on Friday with stabilization changes for connections. My apologies at the delay in release, but we hope that the result will address your issues.
