### ISSUE TITLE
IoTHubRegistryManager.query_iot_hub throws msrest.exceptions.DeserializationError

### ISSUE THREAD

**Issue by asayeedi** [Azure/azure-iot-sdk-python#859]
OS and version used: Windows 10
Python version:  3.9.1
pip version:  20.2.3
azure-core==1.18.0
azure-eventhub==5.6.0
azure-iot-device==2.7.1
azure-iot-hub==2.5.0

Steps to reproduce:

from azure.iot.hub import IoTHubRegistryManager
from azure.iot.hub.protocol.models import QuerySpecification

iotrm = IoTHubRegistryManager(MY_CONNECTION_STRING)
q = QuerySpecification(query="SELECT * FROM devices")
iotrm.query_iot_hub(q)

Result:

Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

**Comment by cartertinney** [comment]
I have been unable to reproduce this issue. It appears that the response you are receiving back from your IoT Hub is formatted in some way that the client is not able to deserialize into a Python object.

Can you add the following lines to the beginning of your application and post the resulting logs:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

Additionally, any information you can provide about your Hub (tier, number of devices, etc.) could be helpful in getting to the bottom of this issue.
