### ISSUE TITLE
Trying to use IoTHubDeviceClient.send_message with a Message throws an exception

### ISSUE THREAD

**Issue by andreashappe** [Azure/azure-iot-sdk-python#934]
# Context

- Ubuntu 21.10
- Python 3.9.7
- VirtualEnv is used, thus:
~~~
Package             Version
------------------- ---------
azure-iot-device    2.9.0
certifi             2021.10.8
charset-normalizer  2.0.10
deprecation         2.1.0
idna                3.3
janus               1.0.0
packaging           21.3
paho-mqtt           1.6.1
pip                 20.3.4
pkg-resources       0.0.0
pyparsing           3.0.7
PySocks             1.7.1
python-dotenv       0.19.2
requests            2.27.1
requests-unixsocket 0.3.0
setuptools          44.1.1
six                 1.16.0
typing-extensions   4.0.1
urllib3             1.26.8
~~~

## Description of the issue

I use code mostly copied form the official documentation and try to use IoTHubDeviceClient.send_message with a Message. This throws an exception.

## Code sample exhibiting the issue

~~~ python
        msg = azure.iot.device.Message(createDeviceToCloudStati())
        # sollte server-seitig gesetzt werden
        # msg.custom_properties["DeviceId"] = registration_id
        msg.content_encoding = "utf-8"
        msg.content_type = "application/json"                                                                                               
        msg.custom_properties["ver"] = "1"
        msg.custom_properties["type"] = "20"
        # API problem: can only be string? not Message? WTF?
        # https://github.com/Azure/azure-iot-sdk-python/blob/main/azure-iot-device/samples/async-hub-scenarios/send_message.py
        await global_device_client.send_message(msg)
~~~

"createDeviceToCloudStati" returns an Array populated with Collections, i.e., should be easily be serializable into JSON.

## Console log of the issue

~~~
future: <Task finished name='Task-17' coro=<statusHeartbeat() done, defined at /home/andy/Projects/VirtualDevice/virtual_device.py:56> exception=ClientError('Unexpected failure')>
Traceback (most recent call last):
  File "/home/andy/Projects/VirtualDevice/env/lib/python3.9/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
    return await callback.completion()
  File "/home/andy/Projects/VirtualDevice/env/lib/python3.9/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
  File "/home/andy/Projects/VirtualDevice/env/lib/python3.9/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 271, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_complete)
  File "/home/andy/Projects/VirtualDevice/env/lib/python3.9/site-packages/azure/iot/device/common/mqtt_transport.py", line 549, in publish
    (rc, mid) = self._mqtt_client.publish(topic=topic, payload=payload, qos=qos)
  File "/home/andy/Projects/VirtualDevice/env/lib/python3.9/site-packages/paho/mqtt/client.py", line 1247, in publish
    raise TypeError(
TypeError: payload must be a string, bytearray, int, float or None.
~~~

**Comment by cartertinney** [comment]
@andreashappe 

We don't currently serialize complex objects that are passed into Message. You must serialize your array of collections.

**Comment by andreashappe** [comment]
@cartertinney : ah.. yes, that fixed it, thank you. Small suggestion: could you throw the exception directly in the Message-constructor? That might make usage clearer, I was debugging the wrong area (if it's okay in principle, I can try to create a patch for that).

**Comment by cartertinney** [comment]
I can probably do something to that effect. I'll try and slip it into the next release.

**Comment by andreashappe** [comment]
perfect! thanks

**Comment by andreashappe** [comment]
(I have closed the issue, hopefully this is the correct workflow)
