### ISSUE TITLE
[Transparent gateway] not able to connect leaf device to gateway with gatewayhostname.local

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-python#988]
I have my downstream device set up which connects using below code to the gateway.
```
  self.device_client = IoTHubDeviceClient.create_from_x509_certificate(
                x509=x509, 
                hostname=hostname,
                device_id='testdevice',
                server_verification_cert=root_ca_cert,
                gateway_hostname=gatewayHostname
            )
```

Unfortunately its not able to connect to the gateway and below is the error log:-

```
Forwarding message to IoThub
Connecting to Hub...
Starting ConnectOperation on the pipeline
Starting run_op in pipeline thread
ReconnectStage(ConnectOperation): State changes DISCONNECTED -> CONNECTING. Sending op down
ConnectionLockStage(ConnectOperation): blocking
MQTTTransportStage(ConnectOperation): connecting
MQTTTransportStage(ConnectOperation): Starting watchdog
connecting to mqtt broker
Connect using port 8883 (TCP)
Forcing paho disconnect to prevent it from automatically reconnecting
Done forcing paho disconnect
transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 391, in connect
    host=self._hostname, port=8883, keepalive=self._keep_alive
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 189, in _run_op
    self.transport.connect(password=password)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 413, in connect
    raise exceptions.ConnectionFailedError() from e
azure.iot.device.common.transport_exceptions.ConnectionFailedError

MQTTTransportStage(ConnectOperation): cancelling watchdog
ConnectOperation: completing with error
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error:
ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
ConnectionLockStage(ConnectOperation): processing 0 items in queue for error=
ReconnectStage(ConnectOperation): failed, state change CONNECTING -> DISCONNECTED
Starting on_complete in callback thread
Callback completed with error
['azure.iot.device.common.transport_exceptions.ConnectionFailedError\n']
******************* Exception
Could not connect to IoTHub
HANDLER (CLIENT_EVENT): Successfully completed invocation

```

I'm able to successfully run the open ssl command `openssl s_client -connect amit-virtualbox.local:8883 -CAfile /var/secrets/downstreamdevice/root_ca.pem -showcerts` and output of which is below:-

```

CONNECTED(00000003)
depth=2 CN = abcd Gateway Devices Root CA
verify return:1
depth=1 CN = abcd Gateway Devices Intermediate CA
verify return:1
depth=0 CN = amit-virtualbox.local
verify return:1
---
Certificate chain
 0 s:CN = amit-virtualbox.local
   i:CN = abcd Gateway Devices Intermediate CA
-----BEGIN CERTIFICATE-----
MIICSjCCAfGgAwIBAgIBADAKBggqhkjOPQQDAjAvMS0wKwYDVQQDEyRWZWxpIEdh
dGV3YXkgRGV2aWNlcyBJbnRlcm1lZGlhdGUgQ0EwHhcNMjIwNDE0MTEzOTE5WhcN
MjIwNTE0MTEzOTE5WjAgMR4wHAYDVQQDDBVhbWl0LXZpcnR1YWxib3gubG9jYWww
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC97KASFGCR4fgXQHBrXAhH
Z9jCaFmqkyNV2p99gyxG6bdfFSqcDm3ZzG4RCJ7Q6KaLtb85372m9z3XEPFFEPnE
JlJ+cnSGraSChW9OeaVKa/LIoDH9JyJC0jOFFZMQNxdc6ZegFw8sAq+coF8JQTLe
+4vWd1i81/i/qFSJkVUUxJixo1yR39/s63DWc+vxxEAOrNteMYmyXm90NVOHSq6x
M4jDQAYKUcnPTqZrFWAxSvnt4hMfgeNyw3QV3nr2cRwF/SzojFsjxF4nKgLedoZr
pYUUg7eqgoIW14Nj3jN3NtnG000xVUEA1klaKLWkjJdq+JXeCalBI80ifoiCNicH
AgMBAAGjQjBAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCkGA1UdEQQiMCCCB2VkZ2Vo
dWKCFWFtaXQtdmlydHVhbGJveC5sb2NhbDAKBggqhkjOPQQDAgNHADBEAiAzVU6+
ZCHqwq1yOP8giaFoxPzzcTs6lCWli0+xbcWzrAIgFWCrJyAqDtG8K6rDbH8Q1KLh
CmQ2dmcqGmhLMAUIqh8=
-----END CERTIFICATE-----
 1 s:CN = abcd Gateway Devices Intermediate CA
   i:CN = abcd Gateway Devices Root CA
-----BEGIN CERTIFICATE-----
MIIBvjCCAWOgAwIBAgIRAMuoMwh4s7LQROik0crmL9owCgYIKoZIzj0EAwIwJzEl
MCMGA1UEAxMcVmVsaSBHYXRld2F5IERldmljZXMgUm9vdCBDQTAgFw0yMjAzMTQw
ODEyMTRaGA8yMTIyMDIxODA4MTIxNFowLzEtMCsGA1UEAxMkVmVsaSBHYXRld2F5
IERldmljZXMgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEeqpUZEzOKA4ylSyG2WaeHQcNxGkVZkC9vvFJKgKNW2WnDAsGsGzSiSWHq3tg
mt4SUU/uj4Boq5SxhfiauPWUS6NmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
/wQIMAYBAf8CAQAwHQYDVR0OBBYEFPCwQo7chhpc0oUBwsOkjgPtviYSMB8GA1Ud
IwQYMBaAFCqD8u3kUR5DJ84J5Q24R6hIxO/XMAoGCCqGSM49BAMCA0kAMEYCIQD0
XIya7XbLTYJNeyiimGnIL9Dld+1+OYMPreYX0UMF5wIhAOqCIMZfo3Wz+gKAC73b
ZeQlUbF+4qYMhYg7R83hdFKG
-----END CERTIFICATE-----
---
Server certificate
subject=CN = amit-virtualbox.local

issuer=CN = abcd Gateway Devices Intermediate CA

---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1731 bytes and written 418 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 8CA83B027E59784DE8357F645E75BCF4BE7D2112587A27D90F49C8880D75CA7F
    Session-ID-ctx:
    Master-Key: DA04D6998B5B899CA5BBB245FCAEDEF7E6B827D7F7818CE550E39B133DB7BD3BCB608B695054523012742E8E1A99D4C0
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 0d 36 50 c7 0e 7e 1f 81-99 db 51 2e ae 6b 95 e1   .6P..~....Q..k..
    0010 - b8 bc d2 4a f3 9c c9 dc-fa 4f b3 17 53 8c 72 96   ...J.....O..S.r.
    0020 - 8b 43 0c de 23 5c 63 0e-d7 91 39 86 ae e9 cc 85   .C..#\c...9.....
    0030 - a3 24 69 f7 09 bc 55 d0-28 a8 f6 f2 cc df 77 76   .$i...U.(.....wv
    0040 - 87 82 2e a0 f1 f2 a6 46-a5 a7 98 76 31 e1 02 ab   .......F...v1...
    0050 - 06 60 49 05 62 29 98 55-ec 05 6c 27 7e 06 23 0a   .`I.b).U..l'~.#.
    0060 - 41 b7 0c ed fb c5 d9 ee-58 31 22 37 69 10 74 ee   A.......X1"7i.t.
    0070 - 5b 1a 23 51 3e 3b 17 81-40 87 2f 5d 1d d3 70 a2   [.#Q>;..@./]..p.
    0080 - 63 c0 8f 7b c6 56 65 fd-9e ec 91 a0 17 cb e5 53   c..{.Ve........S
    0090 - 81 09 8f b5 9f 39 c5 83-8a dc e3 70 ea a0 f9 51   .....9.....p...Q

    Start Time: 1649937682
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)

```

FYI:-

1) I have installed `avahi-daemon package` to do look up of gateway on `hostname.local` .
2) I'm able to ping gateway from leaf device using `gatewayhostname.local`.
3) My leaf device python code is running inside docker container which is giving the issue `socket.gaierror: [Errno -2] Name or service not known` as shown in logs above.

Questions:-

1) In leaf device(docker container) do I need to do anything extra so that the leaf device can connect/resolve the dns name of gateway?

2) Am I doing it correctly? Has this been tried before i.e. leaf device is unaware of gatewayip and it just connects with the hostname which is resolved to an IP by avahi-daemon service.

**Comment by cartertinney** [comment]
@amit12cool 

I suspect the issue is probably with trying to use an IP address rather than a alphabetical hostname. Can you specify exactly what format you are providing the hostname in?

**Comment by Mikkolehtimaki** [comment]
What version of Edge Runtime is your gateway running? I see hostname errors with Edge Runtime 1.2 whereas 1.1 works.

**Comment by cartertinney** [comment]
@amit12cool

Any follow ups to the above questions from me? I also second the question regarding Edge Runtime 1.2 vs 1.1. We will have to close this issue due to inactivity if we do not hear from you soon.

**Comment by amit12cool** [comment]
Yes, edge runtime 1.1 works. Thanks
